### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by p-yukusai** [Lymphatus/caesium-image-compressor#103]
I would love to see the addition of a dark theme to Caesium, since I compress a lot of images and staring at a completely white GUI during that time is really hard on the eyes 😄 
There are various stylesheets and palettes available for this purpose, so writing the qss file wouldn't be much of an issue, see for instance [this](https://github.com/GTRONICK/QSS) repo.

Lovely work and I hope to see this get even better!

**Comment by Lymphatus** [comment]
I totally agree with you.
Funny enough, Qt has native dark theme support for MacOS, but not for Windows. I hoped for a while that there was an official theme without writing my own QSS - which tends to be tedious and breaks often - but seems not.

The repo you linked is looking interesting, I'll give it a shot.

**Comment by AA-Admiral** [comment]
I also 2nd this and hope to see this implemented soon 👍

**Comment by Lymphatus** [comment]
Right now I just implemented the _Fusion_ style from Qt, without any changes. It is not that pretty to be honest, but it's something. I'll take the time to tweak the QSS and palette on a later stage.

For the stable release of the 2.0.0 version there will be some sort of dark theme for sure.

**Comment by Lymphatus** [comment]
Release with v2.0.0-rc.1
As I said it's very unpolished, I'm planning to improve it in the future. Keeping this issue open for comments/feedbacks.
