### ISSUE TITLE
Create a plug-in to integrate in GIMP

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [Lymphatus/caesium-image-compressor#11]
With this plugin Caesium would be possible to load image directly from GIMP if you edited it, and then optimize it. GIMP website has some docs related to this.
https://www.gimp.org/docs/plug-in/plug-in.html

**Comment by Cotihero** [comment]
This project is dead lol. I'd love for him to come back though.

**Comment by Lymphatus** [comment]
This would suit better [caesium-clt](https://github.com/Lymphatus/caesium-clt)
