### ISSUE TITLE
Make it available at winget

### ISSUE THREAD

**Issue by robsonsobral** [Lymphatus/caesium-image-compressor#110]
I guess the title says everything.

**Comment by robsonsobral** [comment]
```bash
$ winget search caesium
Nome      ID                  Versão Origem
--------------------------------------------
CaesiumPH SaeraSoft.CaesiumPH 0.9.5  winget
```

So, try `winget install SaeraSoft.CaesiumPH`

**Comment by Lymphatus** [comment]
[CaesiumPH](https://github.com/Lymphatus/CaesiumPH) is a whole different software that is no longer maintained. I'm not sure how is available on winget, probably a community made effort.

**Comment by robsonsobral** [comment]
So... should we reopen this?

**Comment by Lymphatus** [comment]
Yes, this repo is not on winget and it's something useful. As for #39 for Chocolatey, I'll wait for the stable release.

**Comment by Lymphatus** [comment]
I made https://github.com/microsoft/winget-pkgs/pull/63547 and was correctly merged. I think it's just a matter of time before Caesium shows up in the winget database.
