### ISSUE TITLE
[Win v2.0.0-rc.1] Path issue with the portable zip file

### ISSUE THREAD

**Issue by hu3rror** [Lymphatus/caesium-image-compressor#112]
**Describe the bug**

**Software version**
v2.0.0-rc.1

**Operating System information**
 - OS: Windows 11

**To Reproduce**
1. Open 'caesium-image-compressor-2.0.0-rc.1-win.zip'
2. The first level folder is '..'

**Expected behavior**
Hopefully the first level folder is `caesium-image-compressor-2.0.0-rc.1-win/`
Correct naming could reduce uncertainty errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/19755727/166849102-aa5d1459-c566-4653-9393-a1cedd378a67.png)
![image](https://user-images.githubusercontent.com/19755727/166849352-359c35b0-10a0-47ae-9526-20258ad1c584.png)

**Comment by Lymphatus** [comment]
I re-uploaded the zip archive with the correct path. Thanks for the feedback!
