### ISSUE TITLE
Arabic translations

### ISSUE THREAD

**Issue by shawkynasr** [Lymphatus/caesium-image-compressor#119]
[caesium_ar_EG.zip](https://github.com/Lymphatus/caesium-image-compressor/files/8783954/caesium_ar_EG.zip)

There are one line, I don't know add translation or not?
```
    <message>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;⚠️ Changes will apply after restart&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="vanished">&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;⚠️ Changes will apply after restart&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
```

**Comment by shawkynasr** [comment]
Ok, I didn't translated that line.
You are welcome, so the file ready to using it.

**Comment by shawkynasr** [comment]
> 

Ok, I will add the translation to new file. 

> Is "العامية المصرية" correct?`

not correct, that mean [Egyptian Arabic](https://en.wikipedia.org/wiki/Egyptian_Arabic) locally known as Colloquial Egyptian, right one "**Arabic**"

**Comment by shawkynasr** [comment]
> 

Correct, ` العَرَبِيَّة`

**Comment by shawkynasr** [comment]
> > 
> 
> Correct, ` العَرَبِيَّة`

if there are problem showing Arabic vocalization, you can use `العربية` that without vocalization.

**Comment by Lymphatus** [comment]
Added to Caesium, thanks for you work!
