### ISSUE TITLE
Can't start with version 2.0.0

### ISSUE THREAD

**Issue by Teezton** [Lymphatus/caesium-image-compressor#122]
I get this error when trying to start _Caesium Image Compressor.exe_

![Image 001](https://user-images.githubusercontent.com/5905860/173203252-959cc7a3-76dd-4716-a65e-4b1805933f24.png)

Windows 7 x64

**Comment by Lymphatus** [comment]
It may be a problem with Visual C++ Redistributable. Try to install the latest version found [here](https://docs.microsoft.com/it-it/cpp/windows/latest-supported-vc-redist).
