### ISSUE TITLE
Not all images compressing in 2.0.0, but 1.7.0 version can do it

### ISSUE THREAD

**Issue by zappere50** [Lymphatus/caesium-image-compressor#125]

**Comment by Lymphatus** [comment]
Hi,

can you please give additional context? For example, do the the non-compressed pictures have a red icon on the left o an orange one? Can you provide at least one of them so I can test it myself?

Thanks!

**Comment by zappere50** [comment]
I tried to send one picture to check on it, but I downloaded this sent picture from GitHub,tried it on him and it compressed. You can try download muptiple puctures from anywhere, and try to create this problem.

I am using Windows 10

**Comment by Lymphatus** [comment]
You should try to zip your original files that fails, so you are sure they are not modified.

**Comment by zappere50** [comment]
They were downloaded, and not even modified

**Comment by Lymphatus** [comment]
I cannot be helpful if I cannot test the actual images that are failing. Can you give me one of them? Or the link for downloading one, please?

**Comment by zappere50** [comment]
These pictues are NSFW, which you probably won't like to see, so i can't :D

**Comment by Lymphatus** [comment]
Oh, all right.
Try to upload you application log then, you should find it in
`C:/Users/USERNAME/AppData/Roaming/SaeraSoft/Caesium Image Compressor/caesium-yyyy-mm-dd.log`
Replace `USERNAME` with your username and pick the correct file based on the date. I can try to help with it.

Unless the file names are NSFW too.

**Comment by zappere50** [comment]
File names NSFW too 👀

**Comment by zappere50** [comment]
Ok, i found at least one picture with not NSFW name, so there is log
[caesium-2022-06-14.log](https://github.com/Lymphatus/caesium-image-compressor/files/8901750/caesium-2022-06-14.log)

**Comment by Lymphatus** [comment]
Should be fixed in [v2.1.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.1.0)

**Comment by zappere50** [comment]
aight, thanks 👍🏻
