### ISSUE TITLE
Since v2.0.0-beta4, .webp cannot be read

### ISSUE THREAD

**Issue by handadesu** [Lymphatus/caesium-image-compressor#126]
Hello.
I'm not good at English.sorry.
![beta3](https://user-images.githubusercontent.com/48980145/173591365-3d18d143-d29f-41db-9591-b6391bed2f8e.jpg)
![beta4](https://user-images.githubusercontent.com/48980145/173591405-12ca484c-6ef8-4b48-8b14-e6b1c0a5f1ce.jpg)
![2 0 0](https://user-images.githubusercontent.com/48980145/173591429-0062bdf7-fa1f-423e-b4a2-2d02d5c0bac5.jpg)

**Comment by Lymphatus** [comment]
I tested and it's a bug. I'm working aon a fix for the next release.

**Comment by Lymphatus** [comment]
Should be fixed on [v2.1.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.1.0)
