### ISSUE TITLE
Caesium 2.0.0.0 crash when convert

### ISSUE THREAD

**Issue by Asgatlat** [Lymphatus/caesium-image-compressor#127]
see log attached
i use the zip version of caesium
it closed without error message
[caesium-2022-06-17.log](https://github.com/Lymphatus/caesium-image-compressor/files/8925546/caesium-2022-06-17.log)
d

**Comment by Lymphatus** [comment]
The log you attached is for the 17 of June, and shows only - as far as I can tell - that you opened and closed the application, without any issue.
You said it crashed when compressing, so maybe it was another day with another log?

**Comment by Lymphatus** [comment]
Closing in favour of #128
