### ISSUE TITLE
Software crashing when trying to compress in 2.1.0

### ISSUE THREAD

**Issue by zappere50** [Lymphatus/caesium-image-compressor#128]
**Describe the bug**
The program crashes and closes immediately after a compression attempt.

**Software version**
The version of Caesium Image Compressor: 2.1.0

**Operating System information**
 - OS: Windows
 - Version: 10

**To Reproduce**
1. Download 2.1.0 version,install
2. Add any pictures to list
3. Choose Output folder
4. Press Compress
5. After a couple of seconds, the program should instantly close.

**Screenshots**
Can't take screenshots. No any errors pop up. The program just instantly closes

**Application Log**
Here is couple of them (idk why two, but might be useful :D)
[caesium-2022-06-18.log](https://github.com/Lymphatus/caesium-image-compressor/files/8933894/caesium-2022-06-18.log)
[caesium-2022-06-18.log](https://github.com/Lymphatus/caesium-image-compressor/files/8933895/caesium-2022-06-18.log)

P.s. After updating from 2.0.0 to 2.1.0, my pc just restarted for no reason. Is there any explanation for this?

**Comment by Lymphatus** [comment]
Seems a problem with some PNG images. Do you have any of them so I can test myself?

About the restart: the new installer tries to install Visual C++ Redistributable, but should not restart the PC. I test with various machines and did not get a restart, don't really know the cause.

**Comment by zappere50** [comment]
Try that. Just found on Google. I was trying to compress it right now and the program crashed 
![a0f433603c8a62e9df3d7d25d3b3649e](https://user-images.githubusercontent.com/83653958/174447667-414229cd-382e-459a-ba4e-579f2c621885.png)

**Comment by Lymphatus** [comment]
Weird, compresses fine on my machine. Does it always crash with that image or just at "random"?

Did you try with that image only?

**Comment by zappere50** [comment]
Always. Especially with PNG ones. Tried different PNG images. Still crashing

**Comment by zappere50** [comment]
I can record video or you, and you will see how it happens.

**Comment by zappere50** [comment]
https://user-images.githubusercontent.com/83653958/174449734-8f282814-5103-43a3-bd53-ce0d68e2a6b8.mp4

**Comment by Lymphatus** [comment]
Thanks for the video. Seems there's nothing wrong on your side but something weird with the compression library. I'll do a few more testing and see what I can figure out.

**Comment by Lymphatus** [comment]
@zappere50 is the app crashing with the same image in 2.0.0? Is it compressing or showing an error?

**Comment by zappere50** [comment]
Yes, it's a crash with the same images.  It tries to compress, but as I showed in the video, it just closes automatically.

**Comment by Asgatlat** [comment]
hi,
i got the same behaviour with 2.0.0 as i said in my topic : https://github.com/Lymphatus/caesium-image-compressor/issues/127

**Comment by Lymphatus** [comment]
I can't really reproduce the issue on my machines, but it might be related to the compression library for PNG files.
Caesium internally uses [this PNG library](https://github.com/shssoichiro/oxipng). Is there any chance you can try to compress the files that causes the crash directly with it and see if it's fine?

**Comment by zappere50** [comment]
This one doesn't start. Launching command prompt and automatically closes

**Comment by Asgatlat** [comment]
> I can't really reproduce the issue on my machines, but it might be related to the compression library for PNG files. Caesium internally uses [this PNG library](https://github.com/shssoichiro/oxipng). Is there any chance you can try to compress the files that causes the crash directly with it and see if it's fine?

for me it crashed with JPG files

**Comment by st1np** [comment]
@Lymphatus, i have the same bug!


> bandicam.2022-06-19.00-22-49-885.mp4

**Comment by Lymphatus** [comment]
I changed a few things on v2.2.0 and *should* be fixed. Let me know.

**Comment by zappere50** [comment]
Tried to compress over 200 images. Looks like it's fixed. There were no crashes and images were compressed normally
