### ISSUE TITLE
No preview with portable version / no compressed preview with win 11

### ISSUE THREAD

**Issue by tomkn** [Lymphatus/caesium-image-compressor#129]
**Describe the bug**
Using the portable version does not show the original (left) or the compressed preview (right) after click
Using the installed version shows the original (left) but not the compressed preview after click

**Software version**
2.1.0

**Operating System information**
 - OS: windows 
 - Version 11 pro 64 bit

**To Reproduce**

**Expected behavior**
After clicking on an entry show original (left) and compressed preview (right) according to settings

**Screenshots**
![grafik](https://user-images.githubusercontent.com/29139243/175015633-a860d8f4-d485-48f5-b0de-6900f8b71850.png)

**Application Log**
just shows starting / starting uo / closing

**Additional context**

**Comment by jairbubbles** [comment]
Please not that after installing the version, it's also working correctly with the portable version. If I uninstall it, it still works with the portable version. Probably something to do with the vc redist.

**Comment by Lymphatus** [comment]
Should be fixed in v2.2.0
