### ISSUE TITLE
No update option from 1.7.0 to 2.X

### ISSUE THREAD

**Issue by Asgatlat** [Lymphatus/caesium-image-compressor#132]
Hello,

when you check update from 1.7, there is no informations about the new version
people who used the old version will not be noticed about the new version :( 

![image](https://user-images.githubusercontent.com/86599367/175494975-624c3e3e-ce10-47bf-a561-0ea52108db6f.png)

**Comment by Lymphatus** [comment]
I'm planning to add a direct update from v1.7.0 to the v2.3.0
