### ISSUE TITLE
Update Caesium in Portable app at 2.1 version

### ISSUE THREAD

**Issue by Denisov21** [Lymphatus/caesium-image-compressor#133]
Hi, in Portable app now I can download caesium 1.7. I think https://portableapps.com/apps/graphics_pictures/caesium-portable
I think you should upgrade to version 2.1

Thank

**Comment by Lymphatus** [comment]
I'm not the owner of the software in that website, so I can't directly upgrade the version.
Also, I advise all to download Caesium only from [this source](https://www.fosshub.com/Caesium-Image-Compressor.html) - that is directly managed by me - or from [Github Releases](https://github.com/Lymphatus/caesium-image-compressor/releases). Every other website hosting the download is unchecked and untrusted.
