### ISSUE TITLE
[Feature request]auto rename options in output section

### ISSUE THREAD

**Issue by PaTTeeL** [Lymphatus/caesium-image-compressor#144]
**Is your feature request related to a problem? Please describe.**
When I'm going to compress a image file by resizing it, I just want to keep the original file as caesium 1.7.0 did while there are no suffix option at output section in new versions.

**Describe the solution you'd like**
So could you please put the suffix option back to make it easier for me to resize images in a batch and keeps the original image ?

![屏幕截图 2022-08-22 022410](https://user-images.githubusercontent.com/9150277/185805404-265ca973-4538-479d-adae-98ff01d136e2.jpg)

**Comment by PaTTeeL** [comment]
I just found the suffix option, sorry for mistake.

**Comment by Eyion** [comment]
Make it capable of complex renaming tasks, such as changing a good man to a-good-man, yes, adding "-" between words
