### ISSUE TITLE
Broken i18n file

### ISSUE THREAD

**Issue by FHU-yezi** [Lymphatus/caesium-image-compressor#145]
**Describe the bug**
At file `caesium-image-compressor-main/resources/i18n/caesium_tr_TR.ts`, line 90 for my case.

The content of original file (part):

```xml
        <location filename="../../build_dir/caesium_image_compressor_autogen/include/ui_MainWindow.h" line="955"/>
        <source>JPEG</source>
        <translation type="unfinished"JPEG</translation>
    </message>
    <message>
        <location filename="../../views/MainWindow.ui" line="258"/>
```

An left angle bracket is never closed, which will cause a ParseError when compiling.

It should be that:

```xml
        <location filename="../../build_dir/caesium_image_compressor_autogen/include/ui_MainWindow.h" line="955"/>
        <source>JPEG</source>
        <translation type="unfinished">JPEG</translation>
    </message>
    <message>
        <location filename="../../views/MainWindow.ui" line="258"/>
```

Just add a right bracket and close this tag.

**Software version**
v2.1.0 or ac330ec for the commit hash

**Operating System information**
 - OS: Manjaro with KDE desktop environment
 - Version: As you know, Manjaro is a rolling update distro :smile: 

**To Reproduce**
Just download source code from GitHub and try to compile it.

**Expected behavior**
Got a compiled binary file to install.

**Comment by Lymphatus** [comment]
Fixed in [265cad3](https://github.com/Lymphatus/caesium-image-compressor/commit/265cad37ada31b0e0a3026fda75a26480c0ca3f2)
Thanks for reporting!
