### ISSUE TITLE
2.20 not starting - missing dlls

### ISSUE THREAD

**Issue by tomkn** [Lymphatus/caesium-image-compressor#149]
Hello,

thanks for new release. 
Unfortunately I cannot start it (portable / installed).

I get errors :
execution cannot continue due to missing libgcc_s_seh-1.dll 
execution cannot continue due to missing libstdc++-6.dll 

Am I missing something ?

Best regards
tom

**Comment by Lymphatus** [comment]
Was a bug, I fixed the binary files. See #148 

Please download the installer/portable again from https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.2.0

Sorry for the issue.
