### ISSUE TITLE
Hope to achieve mouse drag folder to caesium

### ISSUE THREAD

**Issue by chillxxxxxx** [Lymphatus/caesium-image-compressor#150]
It will be very convenient

**Comment by Lymphatus** [comment]
This should be already implemented. I just tried on v2.2.0 Windows, and dragging a folder from the File Explorer to the list (only on the list, you cannot drop anywhere) works just fine.

If isn't for you, it might be a bug.

**Comment by Asgatlat** [comment]
I confirm.
I use this since 1.7.0 and it has always worked for me

**Comment by chillxxxxxx** [comment]
<img width="762" alt="NVIDIA_Share_ocVa6jD6OH" src="https://user-images.githubusercontent.com/113571807/190845527-8858237a-4650-4bd5-a210-fee8acda889d.png">
<img width="830" alt="NVIDIA_Share_FhbT7bJ34k" src="https://user-images.githubusercontent.com/113571807/190845534-1dca85a7-a4a2-4837-8a7e-02aa52996104.png">

I uninstalled the old version (2.2.0) and reinstalled 2.2.1,
maybe this error only happens on my pc.

**Comment by Lymphatus** [comment]
Are you on Windows 10 using the default file manager?

**Comment by chillxxxxxx** [comment]
> Are you on Windows 10 using the default file manager?

sure  :D

**Comment by chillxxxxxx** [comment]
> It's not clear from the screenshot so I'm asking: are you trying to add files and folders mixed together? For example multiple files and a folder? Because that won't work.

Maybe I didn't express it well.  
What I mean is that the mouse directly drags the folder or  (single or multiple) image file, it cannot be loaded into the program. 
These two screenshots mean that dragging folders or files into the program is not feasible.

**Comment by Lymphatus** [comment]
Yes, it's a bit strange because should be something already there. Below you can see a video of me doing the drag&drop from the File Explorer without issues. Is that not working for you?

https://user-images.githubusercontent.com/12133996/191374589-4d8cca7a-d9f4-4a5c-90a5-c80f02f8aadd.mp4

**Comment by chillxxxxxx** [comment]
> 
I enable this in group policy -> "User Account Control: Run all administrators in admin approval mode" *
Then after restarting the computer, I can achieve the same operation in your video, it worked!
But at the same time, some other software on the computer is warning me for using super administrator privileges.
I had to turn off this policy and restart the computer again :(
But I was surprised to find that dragging the picture to Caesium is still feasible！
I don't know if the problem is software or computer related.But now it works fine, no need to run as administrator~
Hope I can give you some valuable reference information.
Thank you very much for your patience in answering.
Wish you a happy life :D

*Reference from : [https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/user-account-control-run-all-administrators-in-admin-approval-mode](url)

**Comment by Lymphatus** [comment]
I thought it could be something related to permissions, but I was not aware of that. Glad it's now solved and may be useful as reference for other people. Thanks!
