### ISSUE TITLE
Double entry for remove in menu/toolbar in German translation

### ISSUE THREAD

**Issue by tomkn** [Lymphatus/caesium-image-compressor#151]
Hello,

the program and installers work fine. Excellent tool.

Just to beautify it :
The entry remove seems to be twice in menu / toolbar.

**Comment by tomkn** [comment]
Thanks for fast reply.

This is a misunderstanding.

Ist good to have them in both, toolbar and menu.

But there are 2 entry remove in toolbar and 2 in menu

 

 

 

Von: Matteo Paonessa ***@***.*** 
Gesendet: Donnerstag, 15. September 2022 09:51
An: Lymphatus/caesium-image-compressor ***@***.***>
Cc: tom knauf ***@***.***>; Author ***@***.***>
Betreff: Re: [Lymphatus/caesium-image-compressor] Double entry for remove in menu/toolbar (Issue #151)

 

All toolbar entries are doubled in the menu if you look at them (add, add folder, clear, etc...), because you can actually hide the toolbar and you would need a way to access to those commands.

**Comment by Lymphatus** [comment]
Do you have a screenshot of this? I can only see the Remove and Clear options, that do two seprate things of course.

**Comment by tomkn** [comment]
Sorry, my fault !

 

„Entfernen“ (-) is remove, „Entfernen“ (X) is clear

Remove = „1 entfernen“

Clear = „alle entfernen“

 

Sorry again

 

 

Von: Matteo Paonessa ***@***.*** 
Gesendet: Donnerstag, 15. September 2022 10:42
An: Lymphatus/caesium-image-compressor ***@***.***>
Cc: tom knauf ***@***.***>; Author ***@***.***>
Betreff: Re: [Lymphatus/caesium-image-compressor] Double entry for remove in menu/toolbar (Issue #151)

 

Do you have a screenshot of this? I can only see the Remove and Clear options, that do two seprate things of course.

**Comment by Lymphatus** [comment]
Oh I get it, the German translation is ambiguous. 
The "Remove (-)" will remove the selected items from the list
The "Clear (x)" will remove all of them (it's the same thing as selecting all images on the list and clicking "Remove (-)")
Do you suggest any changes to the translation to make it better?

**Comment by tomkn** [comment]
Remove = „1 entfernen“ or „entfernen“

Clear = „alle entfernen“ or „Liste leeren“

 

 

Von: Matteo Paonessa ***@***.*** 
Gesendet: Donnerstag, 15. September 2022 11:27
An: Lymphatus/caesium-image-compressor ***@***.***>
Cc: tom knauf ***@***.***>; Author ***@***.***>
Betreff: Re: [Lymphatus/caesium-image-compressor] Double entry for remove in menu/toolbar (Issue #151)

 

Oh I get it, the German translation is ambiguous.
The "Remove (-)" will remove the selected items from the list
The "Clear (x)" will remove all of them (it's the same thing as selecting all images on the list and clicking "Remove (-)")
Do you suggest any changes to the translation to make it better?

**Comment by Lymphatus** [comment]
Fixed in v2.2.1
