### ISSUE TITLE
update not wroking in 2.2.0 ? and not translated

### ISSUE THREAD

**Issue by Asgatlat** [Lymphatus/caesium-image-compressor#152]
**Describe the bug**
unable to reach update server when try to check update + dialog box is still in default OS language instead of selected language in caesium

**Software version**
2.2.0

**Operating System information**
 - OS: Windows 10
 - Version 21H2

**To Reproduce**
go to about and update
1. Go to 'about'
2. Click on 'check for update'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/86599367/190637343-13a832aa-9027-4551-9902-d9e8c1da08fc.png)

**Comment by Lymphatus** [comment]
v2.2.0 has a critical problem with the updater and won't work, unfortunately.
It's fixed on v2.2.1 but you can't upgrade directly from the 2.2.0, you need to download it manually [from here](https://github.com/Lymphatus/caesium-image-compressor/releases)
