### ISSUE TITLE
Drag & Drop start automatically compressing

### ISSUE THREAD

**Issue by gmmedia** [Lymphatus/caesium-image-compressor#156]
**Is your feature request related to a problem? Please describe.**
If I drag & drop an image to the desktop icon, Caesium opens, but the image is not added to the file list.

**Describe the solution you'd like**
I have set my optimal settings in the tool already. Everything is ready to compress.
It would be perfect, if I drag & drop the image to the desktop icon and Caesium automatically compresses the image and closes the tool. The original files moves to the bin...

**Describe alternatives you've considered**
An option to convert all .jpg automatically to webp would be nice.

**Comment by Lymphatus** [comment]
I think a better option for achieving what you are saying is to add a context menu option in the file explorer (like in #26).
So the process would be:
1. Go to the file explorer
2. Select images or folders
3. Right Click -> Compress with Caesium
4. App opens and automatically compresses

This give me the option to set multiple context menu entries, like one for only adding the images without starting the process and one that does all the work automatically.

**Comment by gmmedia** [comment]
I don't know if you can add your items to the new context menu in Windows 11. If not, that's 3 clicks.
Drag&Drop is much faster.

**Comment by Lymphatus** [comment]
> I don't know if you can add your items to the new context menu in Windows 11.

I guess it should be pretty much the same as Win 10, but I hadn't really investigated yet.

You're right about the multiple clicks required, but - intuitively - I would guess that dragging into the icon would just add the files without starting the process, like you do using the file explorer. That's just my opinion on a UX matter.

I may just add an option in the settings that changes the "drop on icon" behaviour between just adding and adding + compressing.

**Comment by gmmedia** [comment]
Yep
> I may just add an option in the settings that changes the "drop on icon" behaviour between just adding and adding + compressing.

**Comment by Lymphatus** [comment]
Added in [v2.3.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.3.0)
