### ISSUE TITLE
Add Brazilian Portuguese to Caesium (translation attached)

### ISSUE THREAD

**Issue by gdsa32** [Lymphatus/caesium-image-compressor#158]
Hi.
I've translated Caesium to Brazilian Portuguese.
I hope you can add it to the app.
I'm also available to translate new or changed strings in future versions.

NOTE:
For the localized language name in "Preferred language" drop-down, you should use "Português do Brasil".

Greetings from Brazil.

[caesium_pt_BR.zip](https://github.com/Lymphatus/caesium-image-compressor/files/9659816/caesium_pt_BR.zip)

**Comment by Lymphatus** [comment]
Hi!
First of all, thanks for you contribution! I'm currently developing the 2.3.0 version, which will add some more lines of text. It would be great if you could wait until I finish with that version and add the remaining lines of text.
It won't take too much, I'll keep you informed.

Thanks again!

**Comment by 41646F6C666F** [comment]
As I'm willing to update two languages, Spanish and French, I subscribe to this issue too.
Grazie mille for this amazing tool @Lymphatus 😉

**Comment by Lymphatus** [comment]
Added in [v2.3.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.3.0)
