### ISSUE TITLE
Feature request: allow to compress only images greater than a certain size

### ISSUE THREAD

**Issue by nephtys59** [Lymphatus/caesium-image-compressor#159]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to NOT compress images lower than a certain file size 
(example: "compress only images greater than 300 kb or 1 mb")

**Describe the solution you'd like**
Add an option to filter out low size images

**Describe alternatives you've considered**
At the moment I'm forced to remove manually from the list all images lower than a certain size before compressing.

**Additional context**
![example](https://user-images.githubusercontent.com/31031583/192869903-60e51d01-63b6-4d23-9a07-eba69761f01b.png)

Please and thank you very much :-)

**Comment by tomkn** [comment]
I agree, would be very useful !
Exspecially if you have a "project directory" with photos from handy, dslr, compressed ones after editing with PSE,...

**Comment by Lymphatus** [comment]
It's gonna be implemented in the next release.

**Comment by Lymphatus** [comment]
Added in [v2.3.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.3.0)
