### ISSUE TITLE
Option to retain file ownership information

### ISSUE THREAD

**Issue by SCSJesse** [Lymphatus/caesium-image-compressor#162]
**Is your feature request related to a problem? Please describe.**
This is not necessarily an issue, but it would be preferred have this option available.

**Describe the solution you'd like**
After compression, the files that have been compressed will display the username of the person who applied the compression.
I don't necessarily want to lose this information and would prefer it remain on the file.

**Describe alternatives you've considered**
Adding information manually to "author" in the properties of a given file can allow me to keep a record of the original supplier of the file, though this can be time consuming on multiple different directories, more so when those files are supplied by different people.

**Additional context**
On Windows 10, right clicking on a file and opening the properties can allow you to add "Authors" under the details tab:
![image](https://user-images.githubusercontent.com/116378230/197255185-f6315e9d-2018-4eaa-9344-1fa1348b95dd.png)

The "Owner" changes whenever a file is copied, but also following compression from any given version of Caesium (1.7 to current):
![image](https://user-images.githubusercontent.com/116378230/197255515-0476c18d-1a7d-4ba4-867b-6061da70793f.png)

**Comment by Lymphatus** [comment]
If you check the "Keep metadata" in the "Compression" tab on the right, the info about the author is preserved along with the other JPG info you might have.
