### ISSUE TITLE
Images rotated by exif data do not keep the orientation in viewer nor in saved file

### ISSUE THREAD

**Issue by dbrasseur-aneo** [Lymphatus/caesium-image-compressor#166]
**Describe the bug**
When an image is rotated by EXIF data, the orientation is not kept. The viewer in the program loads it without the exif data and the program saves it without it, giving it the wrong orientation.
Keeping the exif data or rotating the output should fix that

**Software version**
2.2.1

**Operating System information**
 - OS: Windows
 - Version 10

**To Reproduce**
1. Load this image in the program (it has exif data)
![05426](https://user-images.githubusercontent.com/103190315/203852002-071bbc7b-97c4-4fdd-876c-452835811612.jpg)
2. Click on the image in the list of imported files
3. See that the viewer doesn't give the right orientation
4. Save in a folder
5. See that the saved image doesn't have the right orientation

**Expected behavior**
Viewer should show the right orientation and the saved file should have the right orientation too

**Screenshots**
![image](https://user-images.githubusercontent.com/103190315/203852312-cc7eaf3b-bc50-4c76-aaeb-14ec3191db86.png)

**Application Log**
[caesium-2022-11-24.log](https://github.com/Lymphatus/caesium-image-compressor/files/10086915/caesium-2022-11-24.log)

**Comment by Lymphatus** [comment]
The image is loaded without considering the rotation metadata, so you see it rotated. I'll try a fix for that.
If you check the "Keep Metadata" under the "Compression" tab on the right, the orientation is preserved during compression. I tested with your image and worked fine for me.
<img width="198" alt="Screenshot 2022-11-25 alle 09 57 23" src="https://user-images.githubusercontent.com/12133996/203941076-b6af9542-614b-4eae-b990-d46dd66ee4c4.png">

**Comment by Lymphatus** [comment]
Fixed in [v2.3.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.3.0)
The images have the metadata rotation, but if you don't check `Keep metadata` it will be lost.
