### ISSUE TITLE
New feature: compress image to desired output size (bytes not pixels)

### ISSUE THREAD

**Issue by vekuda** [Lymphatus/caesium-image-compressor#17]
It would be great if - as an alternative to setting the compression rate - the user is allowed to enter the size of the output file and Caesium compresses the file accordingly.

Example: 
_I need a forum avatar to be smaller than 1024 KB, so I enter '1023' in the 'Output size (KB)' box.
Caesium automatically chooses the quality of the compression to meet my demands, and it compresses the picture accordingly.
The output file is approximately 1023 KiloBytes._

This exact feature does already exist in Adobe Lightroom's export settings, but to install / open such an expensive and resource-heavy software only to compress a picture is a bit overkill for most users.

**Comment by Lymphatus** [comment]
This is something I wanted to implement for a very long time. It's quite difficult to not slow down the compression process too much, but it's definitely in the roadmap.

**Comment by AlanSP1** [comment]
That's something that exists in [Advanced JPEG compressor](https://jpeg.compressor.software/).

There you can set size, but also you can set ratio, based from uncompressed image (like, 4000x3000 is 12MP). Not sure if it will help speed things up.

I must say, all your versions work much, much faster than Advanced JPEG compressor. And they give impressive results, too. This feature is really great, deciding how much space we want to give to our pictures is "a must" for this type of software, even if it does slows down process, as is evident with Advanced JPEG compressor.

**Comment by Lymphatus** [comment]
Released on v2.5.0
