### ISSUE TITLE
Move original file to trash (option)

### ISSUE THREAD

**Issue by ArkitectNaut** [Lymphatus/caesium-image-compressor#174]
Option to have original files  moved to trash rather than be over-written.

This would allow the retrieval of the original in case of a problem or whatever.

**Comment by Lymphatus** [comment]
This can be a somewhat useful option.
As an example, you may have several nested folders to compress but want to be sure the results are ok after compressing. You can add a suffix, but then you'll have both original and compressed files alongside each other. If the results are ok for you, you now want to delete all the originals, but might be a long manual process.
Instead, if the originals are moved to trash, you can simply empty the bin and you are good to go. Or if you want to revert, you just select all compressed files and restore the ones from the trash with a click.

**Comment by ArkitectNaut** [comment]
> you may have several nested folders to compress but want to be sure the results are ok after compressing.

Yes, exactly this. Another example is for use with programs that link to a media reather than embed it. By having the old media moved to the trash and the new media replaced with the same name allows for a more seamless experience.

**Comment by Lymphatus** [comment]
Fixed in 2.4.0

**Comment by aeast46** [comment]
Hi 

Can you advise where is the trash on Caesium? Ive compressed a file but cant find the original? 
And its also not in the recycle bin, in Windows itself?
Please help asap
Thanks
Anthony.

**Comment by aeast46** [comment]
Im on version 2.7.1

**Comment by ArkitectNaut** [comment]
The trash is Windows' trash bin but it's an option you have to enable
