### ISSUE TITLE
Where can I download v1.x?

### ISSUE THREAD

**Issue by Darthagnon** [Lymphatus/caesium-image-compressor#175]
### Readme.md:
> Windows: 8.1+ (use old version v1.x for Windows 7)

Where can I download v1.x for my old PC?

NB. I think it might be possible to run v2.x on Win7, despite Qt6 incompbatibility, thanks to [these compatibility hacks](https://forum.qt.io/topic/133002/qt-creator-6-0-1-and-qt-6-2-2-running-on-windows-7)

**Comment by Lymphatus** [comment]
I might add a link to the README for older versions. You can download it from [here](https://www.fosshub.com/Caesium-Image-Compressor-old.html) or [here](https://sourceforge.net/projects/caesium/files/1.7.0/).

Anyway, I strongly advise against using the 1.7.0 as it is no longer maintained. If you need to convert from/to formats, you can use the 2.3.0-beta you can find [here](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.3.0-beta.1).

**Comment by Darthagnon** [comment]
Thank you!
