### ISSUE TITLE
[WIN32] zopflipng.dll not found

### ISSUE THREAD

**Issue by matteotrubini** [Lymphatus/caesium-image-compressor#18]
![screen](https://user-images.githubusercontent.com/7964032/79106220-5c822c00-7d72-11ea-88f7-84c4f3785282.png)

Workaround: rename libzopflipng.dll to zopflipng.dll

**Comment by Lymphatus** [comment]
I updated the archive in the release with the fix. Thanks!

**Comment by MojoCreator** [comment]
I ran into this same issue after downloading the newest archive. Renaming libzopflipng.dll to zopflipng.dll allowed the application to run.

**Comment by Lymphatus** [comment]
@MojoCreator you're right, it's the same issue! My bad, used a wrong release again. I updated the archive with the fix.

**Comment by Deses** [comment]
I still have this problem. 🤔
