### ISSUE TITLE
Compress image then delete original

### ISSUE THREAD

**Issue by 3xploiton3** [Lymphatus/caesium-image-compressor#180]
Can we have feature compress image than delete original, (optional)
https://i.imgur.com/apmS1Us.png

respect options
skip if output size is bigger than the original (not delete original files)

**Comment by masterrite** [comment]
do you mean "compress and _**then**_ delete" or "compress rather **_than_** delete"?

for the first one, doesn't caesium already overwrite the original? for the second one, just add a suffix in the output tab.

don't know what "respect options" means, but "skip if output size is bigger" is already in the output tab. I'm not sure what you're asking for tbh

**Comment by 3xploiton3** [comment]
sorry my english is poor

yeah caesium have overwrite the original and i like this feature when i want compress with the same name files, 
in this case my setting add suffix output, then delete original file without having manual delete, 

"compress and then delete"

**Comment by scheinercc** [comment]
This might be along the same line, but happy to open a separate ticket if not.

From ImageOptim I am used to dragging images into the tool and they will just overwrite the original.

**Comment by Lymphatus** [comment]
Fixed in 2.4.0
