### ISSUE TITLE
If the name of the source folder is in Chinese, the folder path will be lost when importing

### ISSUE THREAD

**Issue by leeaikong** [Lymphatus/caesium-image-compressor#183]
**Describe the bug**

When I import a folder, some files have no path，

No error found when I empty the list and import it again。

Finally, I found that even if the folder is not a Chinese name, the folder path will also be lost

![20230130213207](https://user-images.githubusercontent.com/40814658/215491522-2a3c8ead-8596-4785-9c8d-cb23ca5dbccd.png)

**Software version**
The version of Caesium Image Compressor  2.3.0

**Operating System information**
 win 10

**Comment by Lymphatus** [comment]
Hi! Can you please add some details about the steps you did before encountering the bug?
For example, can you provide me the paths of the folders you added and in what order? Also, did you use the "Add Folder" or "Add files" option?
I tried with some random paths on my device and seemed to be fine, with or without 汉字.

**Comment by leeaikong** [comment]
Using the "Add Folder" or "Add File" option, I found no problem

Dragging a folder into the window will cause the missing folder path

**Comment by Lymphatus** [comment]
I was able to reproduce the issue by importing a folder by dragging and then importing some files (not folders) by dragging too. I'll have a look.

**Comment by leeaikong** [comment]
![pp](https://user-images.githubusercontent.com/40814658/215727653-c9c2490a-7a71-49bc-af67-e85b1b083a91.gif)
The operation video reproduces the error

**Comment by Lymphatus** [comment]
Fixed in [v2.3.1](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.3.1)
