### ISSUE TITLE
Image was accidently rotated

### ISSUE THREAD

**Issue by sti1l-0** [Lymphatus/caesium-image-compressor#187]
**Describe the bug**
I input a image that resolution is 4024*6048, as you can see that is a vertical image.

Whatever "resize to fit" option I use, the output image is always in horizontal resolution like 6048*4024.

**Software version**
The version of Caesium Image Compressor 2.3.1

**Operating System information**
 - OS: Windows
 - Version 11

**To Reproduce**
1. Add a vertical image
2. Select any option you like and compress
3. See error

**Expected behavior**
The image keep its origin direction.

**Screenshots**
![image](https://user-images.githubusercontent.com/37724877/219845921-4f334888-b6c3-425b-b76c-225790731628.png)

**Application Log**
--

**Additional context**
--

**Comment by Lymphatus** [comment]
Does the issue occur if you check the "Keep metadata" checkbox in the compression options?

**Comment by Csrayz** [comment]
When compressing to webp is selected, the image is still incorrectly rotated. Images are not rotated unexpectedly when trying to compress to jpg or png.

![Snipaste_2024-01-08_16-21-40](https://github.com/Lymphatus/caesium-image-compressor/assets/33659823/3387d928-ac1f-4602-b5dd-dcea030f6ede)

Options are as follows:

![Snipaste_2024-01-08_16-21-59](https://github.com/Lymphatus/caesium-image-compressor/assets/33659823/757e6db8-ad62-40f1-baa3-c64cc97dab92)

![Snipaste_2024-01-08_16-22-08](https://github.com/Lymphatus/caesium-image-compressor/assets/33659823/952595a8-69a3-417c-9e94-baf1bc5c2f0e)

![Snipaste_2024-01-08_16-22-28](https://github.com/Lymphatus/caesium-image-compressor/assets/33659823/f50e5f87-6d96-4249-83cc-3bf2d9ae1486)

**Comment by Lymphatus** [comment]
@Csrayz The original image is WebP or any other format?

**Comment by Csrayz** [comment]
> @Csrayz原图是WebP还是其他格式？

The original image is a jpg, and when I tested it, I found that only certain images produced these kinds of strange phenomena. The operation recording and source files are attached below.

https://github.com/Lymphatus/caesium-image-compressor/assets/33659823/e38b28f9-8015-4ec0-a643-b1527d8f8ede

[Photos.zip](https://github.com/Lymphatus/caesium-image-compressor/files/13868570/Photos.zip)

**Comment by Lymphatus** [comment]
This should not happen when the output format is the same as the original file, but can occur if, for example, the original is JPG and the output is WebP. It's related to #196 because Caesium cannot keep the metadata of the original file if is compressing to another format. I'm working on a solution for this.
