### ISSUE TITLE
new language

### ISSUE THREAD

**Issue by All07-07** [Lymphatus/caesium-image-compressor#189]
I added the Slovak language

**Comment by All07-07** [comment]
I added new string in the slovak language

**Comment by Lymphatus** [comment]
@All07-07 Wher do I find the new file?

**Comment by All07-07** [comment]
Sorry, I am beginner on github

It is on 
https://github.com/All07-07/caesium-image-compressor/commit/7178f9a868f7f3da80376a7ac2a86de82155fc94
