### ISSUE TITLE
Window not remembering its size and position in a specific condition.

### ISSUE THREAD

**Issue by medukia** [Lymphatus/caesium-image-compressor#191]
**Describe the bug**
Window not remembering its size and position in a specific condition.

**Software version**
2.3.1 portable

**Operating System information**
Windows 10 64 bit

**To Reproduce**
1. resize the window by dragging the edges for my liking
2. just use Caesium as usual
3. maximize the window by clicking on the icon in the upper right corner of the window
4. close the program
5. restart the program
6. now, you can see the program lose its maximized state and the window gets much bigger than I set it to be (nearly same as maximized)

**Expected behavior**
It is expected to save the size and position of the window and restore it when running the program next time.

**Comment by Lymphatus** [comment]
On my Windows 11 machine, when I maximize the application and then close it, it restores the maximized state, but, if I toggle the maximized state, the application bugs itself like you described. I'll manage a fix.

**Comment by Lymphatus** [comment]
Fixed in 2.4.0
