### ISSUE TITLE
@

### ISSUE THREAD

**Issue by medukia** [Lymphatus/caesium-image-compressor#192]
@

**Comment by medukia** [comment]
sure. here are examples I think will help.

![colorful-original-32](https://user-images.githubusercontent.com/123845934/223472862-bf471110-d14f-479c-a83b-48b10b93b9f0.png)
original, 32bits
![colorful-saesium-compressed-8](https://user-images.githubusercontent.com/123845934/223472872-dabc9f58-c29c-49ef-a8fc-acd82a2ea632.png)
compressed, at 90%, 8bits
![poem-original-32](https://user-images.githubusercontent.com/123845934/223484883-d46efc58-8fdf-42fb-9893-06d0707e0fcd.png)
original, 32bits
![poem-saesium-8bit](https://user-images.githubusercontent.com/123845934/223485246-f977627e-6fad-45d7-8a38-034288809265.png)
compressed, at 90%, 8bits
![poem-saesium-2bit](https://user-images.githubusercontent.com/123845934/223485530-5902538f-dcb4-4248-b5be-ec2a1bcb7ea1.png)
compressed, at 1%, 2bits


You can notice the nature photo's details of gradient background out of focus are heavily damaged, so are the butterflies' red wings.
On the other hand, you can in no way notice any difference between 32bit and 8bit scanned document images although zooming in at 300% or something. and 2bit document still provides quite good quality, hard to notice loss in naked eyes.

So the problem is, in short, that Caesium has difficulty in detecting the type of each images and numbers of colors used to pick the best bit depth, to get the best quality/size ratios. Different type of images gets different compression efficiency at same quality level, which will make it hard to get the overall consistency in same settings profile.

**Comment by Lymphatus** [comment]
I think it's better to use the `lossless` flag for every PNG that has a lot of details/colors, like the first you provided. Running with the quality slider will always decrement the colors and can be an hard hit on quality. That's how the algorithms are tweaked and I think there's no much room for improvement. The "lossy" PNG option is great for images like the second example, where colors are very few.

Another option might be to convert the first example image to something like WebP, which should preserve quality and make it smaller.
