### ISSUE TITLE
win10 can't drag folder in directly

### ISSUE THREAD

**Issue by xzkeee** [Lymphatus/caesium-image-compressor#20]
not in adminsriator mode;
shows a red prohibitory sign

drag works on 1.7.0
![image](https://user-images.githubusercontent.com/17961239/80457077-4e7efe80-8961-11ea-944e-9abd1c1cb1f2.png)

**Comment by Lymphatus** [comment]
Drag is not available in this alpha-1 release. Will be enabled for sure in the upcoming releasese.

**Comment by xzkeee** [comment]
I look forward to new release.Your software made my life easier.

**Comment by Lymphatus** [comment]
Right on time! The feature is in 7eb1f4e commit, in the `alpha-2` branch. Should be shipped with that release.
