### ISSUE TITLE
Crashes when compressing corrupted files

### ISSUE THREAD

**Issue by KillianVbrg** [Lymphatus/caesium-image-compressor#200]
Hi and thank you for your amazing tool! 😍
I am working with huge datasets of photos... And the thing is that some are corrupted (like 1% max). I can't check them all individually of course, and when I use Caesium and it is trying to compress a corrupted file, it crashes 🫤 Is there a way to avoid this? Can be a solution out of Caesium too that I don't know to check the integrity of all the files and delete the corrupted ones? 🥲

Thanks again! 👋

**Comment by Lymphatus** [comment]
Hello! Can you share a couple of corrupted pictures so I can run some tests on them? Thanks!

**Comment by KillianVbrg** [comment]
Ok here are so pictures.
‼️ However, I think I have to warn you in case you manage to preview the compressed files. My dataset is a porn dataset to train an AI model for a porn recognition AI. The images I provides might not be appropriate. ‼️
You're welcome :)

**Comment by KillianVbrg** [comment]
Hi! Ok here is a picture, I'll send others when I run into them.
‼️ However, I think I have to warn you in case you manage to preview the compressed files. My dataset is a porn dataset to train an AI model for a porn recognition AI. The images I provides might not be appropriate. ‼️

You're welcome :)
![2326](https://github.com/Lymphatus/caesium-image-compressor/assets/90329015/c3426339-51d8-4032-9a4a-cf762dd50a42)

**Comment by KillianVbrg** [comment]
Ok here is a picture, I'll send others to you when I run into them.
‼️ However, I think I have to warn you in case you manage to preview the compressed files. My dataset is a porn dataset to train an AI model for a porn recognition AI. The images I provides might not be appropriate. ‼️

You're welcome :)

PS: I am reposting the answer cause GitHub could actually preview the image. So here's the link (so people don't have to see it on this page): https://drive.google.com/file/d/1_hyAekPz8H5ux4dT9gXozQUiJ9P57YbX/view?usp=sharing

**Comment by KillianVbrg** [comment]
Hello!
The app crashed when it ran into those files:
https://drive.google.com/drive/folders/1CjEtClCX7CzCNDxJI25CStO_pkIplHa0?usp=sharing

**Comment by Lymphatus** [comment]
It's a problem with [libcaesium](https://github.com/Lymphatus/libcaesium) not able to handle the corrupted files correctly. I need to fix it there and then ship a bugfix version of the app.

**Comment by Lymphatus** [comment]
Fixed in [v2.4.1](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.4.1)
