### ISSUE TITLE
Error:Unknown file type [png file]

### ISSUE THREAD

**Issue by 3xploiton3** [Lymphatus/caesium-image-compressor#201]
**Describe the bug**
failed to compress png, resolution 20000x7813

**Software version**
The version of Caesium Image Compressor [v 2.4]

**Operating System information**
 - OS: Windows 11

**INFO**
Error:Unknown file type

file test, removed after 7 days:
https://anonymfile.com/JO2W4/nusacococom-20000-transparent.png

**Comment by 3xploiton3** [comment]
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/19517680/9f829f35-1ccc-4b0b-814b-12ba4b3cddd7)

**Comment by 3xploiton3** [comment]
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/19517680/3c2b43ec-c5fc-41cb-beed-76d32caad11a)

issue still exists

**Comment by Lymphatus** [comment]
Can I have a screenshot of the "Output" tab in the options? Also, are you trying to resize?

**Comment by 3xploiton3** [comment]
> Can I have a screenshot of the "Output" tab in the options? Also, are you trying to resize?

i don't use resize

![image](https://github.com/Lymphatus/caesium-image-compressor/assets/19517680/0f2c1f4c-d527-47b1-b04e-b3ea409c283c)

**Comment by Lymphatus** [comment]
Unfortunately the image is too big to be handled by the Qt WebP library. Max size is 16383px, so yours cannot be correctly handled. There's nothing I can do because it's a Qt limitation, so you have to choose another format to compress to or to resize the image a little bit.
