### ISSUE TITLE
Sort and compress in alphabetical order (Windows Explorer's way)

### ISSUE THREAD

**Issue by KillianVbrg** [Lymphatus/caesium-image-compressor#202]
Hi again! 👋
When we have a large amount of files named from 1.jpg to xxxxxx.jpg, the sorting feature doesn't actually sort the way you'd expect it to do. And it is the same for the compression process unfortunately. Why isn't sorting the files like Windows Explorer would? 🫤

It can seems very trivial but think of it that way (I faced the problem). If you PC, or app crashes, with that kind of sorting, you don't really know what files had been compressed or not! Look at my screenshot of the app, the files 10,100,1000, 1001 and 1002 had been compressed. It means that if it crashes now, I cannot start compressing files from a certain file like 567 for example since files before and after this one had been compressed. The other solution would be to make your app remember the files already compressed but it'd still not resolve the unwanted sorting on the UI. 🥲

![Example CIC](https://github.com/Lymphatus/caesium-image-compressor/assets/90329015/0d4399e1-6f35-4f34-8e5f-e00dc8b4d02d)
![Example WE](https://github.com/Lymphatus/caesium-image-compressor/assets/90329015/71db5db2-522e-4e2c-8001-56ef00e79370)

It'd be easier to use the app with a nice sorting for the UI AND for the compression process. 

This is a great tool already anyway, so thank you very much for your work! 😉

**Comment by KillianVbrg** [comment]
Something else, it'd be nice to have the estimated time remaining and the possibility to pause the compression.

**Comment by Lymphatus** [comment]
> Something else, it'd be nice to have the estimated time remaining and the possibility to pause the compression.

The estimated time remaining would be a very wild guess, because we cannot know how much time a files to take to compress. Is related to the file size, but very hard to estimate with an acceptable precision.

> Also being able to choose an action to perform after the compression would be great (like shutting the app down, putting the PC to sleep or turn it off...)
This is something that can be implemented. I will make a separate feature request for this.

**Comment by Lymphatus** [comment]
Fixed in [v2.4.1](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.4.1)
