### ISSUE TITLE
png to jpg failed to compress, result all goes black

### ISSUE THREAD

**Issue by 3xploiton3** [Lymphatus/caesium-image-compressor#204]
original file:
https://drive.google.com/file/d/1svIP6kNiZ_piggpyTys3vTbgJimpjsTW/view?usp=share_link

result file after compress to jpg:
https://drive.google.com/file/d/11mVfrycygup2zDyaXJgngSdrLA2Ooh8p/view?usp=share_link

OS: windows 11 (22H2)
caesium: v2.4.0

config
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/19517680/cde93013-2b03-4c25-b16e-43fdbddb30b1)
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/19517680/a20cd40e-b33c-4a9c-a1f1-76b357fb28de)

**Comment by Lymphatus** [comment]
This is not really a bug, but it's intended.
The PNG image has transparency, which JPEG does not have. The conversion process just takes all transparent pixels and convert them to black. Since the content of the image is itself black, then you have a nice dark square as result.
