### ISSUE TITLE
Ability to choose an action to perform after the compression

### ISSUE THREAD

**Issue by Lymphatus** [Lymphatus/caesium-image-compressor#205]
Also being able to choose an action to perform after the compression would be great (like shutting the app down, putting the PC to sleep or turn it off...)

_Originally posted by @KillianVbrg in https://github.com/Lymphatus/caesium-image-compressor/issues/202#issuecomment-1570400384_

**Comment by BlackGrimReaper** [comment]
+1 for this. What's the status?

**Comment by Lymphatus** [comment]
I wanted to start the development of this for the 2.6.0 version. It's a bit tricky because it's OS dependent, but I think I'll start win Windows, with macOS/Linux after.
I'll probably start with shutting down the app/PC after compression. Any ideas of other options that might be useful?

**Comment by BlackGrimReaper** [comment]
Few options that are coming to my mind are
- Shutdown
- Hibernate
- sleep
- close App only
- Run a .bat file or a custom program/script. This choice is valuable as it opens up many options for post-processing tasks, making things simpler for you in the long run. You won't need to create more custom solutions, and users can take care of it themselves. It would also be helpful if the system could remember the last 5-10 programs/scripts used for a smoother workflow.

**Comment by Lymphatus** [comment]
Added all of the above except for the run of a custom script, which is a little more complicated. I'm still planning it for the future.
