### ISSUE TITLE
cannot running on Windows 8.1?

### ISSUE THREAD

**Issue by lillianacollins** [Lymphatus/caesium-image-compressor#208]
caesium-image-compressor 2.4 or 2.3.1 cannot running on my computer (Windows 8.1 pro) , the error message says 

"The procedure entry point **SystemParametersInfoForDpi** could not be located in the dynamic link library C:\Program Files\caesium image compressor\Qt6Gui.dll"

so how do i resolve this error ? thanks.

**Comment by Lymphatus** [comment]
Unfortunately the README is wrong and the version 2.x.x do not work on Windows 8.1. You should try the [older 1.7.0 version](https://www.fosshub.com/Caesium-Image-Compressor-old.html).

I'm correcting the README right away and sorry for the issue.
