### ISSUE TITLE
Format is reset to "Same as input"

### ISSUE THREAD

**Issue by vivadavid** [Lymphatus/caesium-image-compressor#216]
**Describe the bug**
In _Settings_ > _Output_, I select "JPG" under _Format_. However, every time I reopen Caesium, it's set back to "Same as input".

**Software version**
2.5.1.

**Operating System information**
 - Windows 11.
 - 22H2.

**To Reproduce**
- In _Settings_ > _Output_, I select "JPG" under _Format_.
- I convert an image and everything works as expected.
- Next time I open Caesium, this setting is reset to "Same as input".

**Expected behavior**
I expected the setting to stay the way I chose until I decide to change it again.

**Application Log**
[caesium-2023-07-16.log](https://github.com/Lymphatus/caesium-image-compressor/files/12063877/caesium-2023-07-16.log)

**Comment by Lymphatus** [comment]
A fix is on the main branch, it will be released with the 2.5.0 version.

**Comment by vivadavid** [comment]
Thank you, @Lymphatus !
