### ISSUE TITLE
Compression Option in v2

### ISSUE THREAD

**Issue by MojoCreator** [Lymphatus/caesium-image-compressor#22]
When compressing, most image and design applications leverage the percentage as compression. You had this in the previous version but right now, the UI shows Speed -> Quality with 5 positions. 

It is hard to know what position 3 or 4 would be. How are you quantifying this scale that is being used? It would be nice to have either a quantified scale or a sample image below that adjusts based on the compression quality chosen.

**Comment by Lymphatus** [comment]
Most software use a scale between 1 and 100 and so used Caesium v1. I was initially thinking of switching to a more simple approach for the v2, like the one you saw in this version, but I'm not entirely convinced about it.

This is an open topic for me, so if you (or anyone) have some advices or ideas, I'm here to listen.

**Comment by AlanSP1** [comment]
Well, this is fine for now (as it is "heavy" alpha at the moment still).

You also mentioned planning to add option to compress to desired image size, which would be one option.

Also, you could keep this system and call it "simple", or maybe "coarse" in defining compression, but you could also employ "fine" system with more options, like having usual scale from 1 to 100 (though I personally never did understand what this scale actually means).

There could also be some sort of scale based on how output image would be affected, i.e. changed from original one. Something like, almost same, some artifacts, heavily impacted... so we would know what to expect final image to look like.

**Comment by Lymphatus** [comment]
> (though I personally never did understand what this scale actually means)

That's the point. If you're not a bit into image compression, that scale means absolutely nothing. It's not a percentage and it's barely a scale that defines how much artifacts an image could have (I'm over-simplifying here). Furthermore, two different images compressed at the very same level could differ a lot in terms of quality.

> There could also be some sort of scale based on how output image would be affected, i.e. changed from original one. Something like, almost same, some artifacts, heavily impacted... so we would know what to expect final image to look like

There's also another thing to keep in mind: all I've said applies to JPGs, but not for PNG. The compression algorithm used for PNGs is always lossless, so no artifacts or quality loss, the difference is the size/time ratio. So the sentence I quoted it's ok for JPGs, but cannot be applied to PNGs.

> Also, you could keep this system and call it "simple"

This is my favorite approach, but it's a bit of a nightmare in terms of UX/UI. I'd like to keep a simple slider for casual users (they're a lot), implement the "desired image size" (which cannot be applied for PNGs) and give an "Advanced Mode" for fine tuning.
I just need to figure out how to make it usable UX/UI wise.

**Comment by MojoCreator** [comment]
To be honest, this is all about the users of the application. I would assume that the user base is pretty wide. 

**USAGE**
1. Home Use - Some would use this to decrease the size of their family/personal/work images on their NAS or file service like Dropbox, Google Drive, etc..
2. Photographer Use - They may use it to send low quality images for a customer to review before purchasing the high resolution images.
3. Web Developer - They would use it to maximize visual appeal while minimizing total size, increasing the speed at which a website loads.
4. I am sure there are more...

**SKILLSET**
Beginner
Intermediate
Advanced

I easily fall into #1 and #3 in this list and I am also advanced. I appreciate simplicity but it is also important that the focus of simplicity shouldn't circumvent the Advanced user or the LCD (Lowest Common Denominator). If you have a position on a line for the scale, the user (advanced or beginner) should know what that line represents. The goal is to not make the user run a sample image through on any of those scale points to see what the difference is. They should look at the scale options and know they are making the right decisions based on the facts in front of them. 

It could be as easy as adding a checkbox at the top for Advanced, when checked, there are more details shown on top of the interface. Default can be Beginner but you don't want to ignore an Advanced user base. It's also important to know how you 'know' there are more beginners than advanced users. I would assume, you would hear more from the beginners than the advanced users so is it possible you have a possible data gap for advanced users?

In the end, determining who you are developing the UI for will help you plan out the UX. Great work so far!

**Comment by Lymphatus** [comment]
First of all, thanks for the feedbacks. They **really** help.

The very first Caesium version came out over 10 years ago and I made the terrible mistake to not collect enough feedbacks and "data" about the average user. Right now I can only assume who they are based on a few assumptions. That's why I'm so doubtful about some design patterns.

> It could be as easy as adding a checkbox at the top for Advanced, when checked, there are more details shown on top of the interface.

^ This. I'm going to focus on this aspect for the next alpha release. One of the first ideas I (and a few friends of mine) had for the new version was to have two different _modes_ as your said. I'm gonna iterate through a few possible solutions in the next days.

Caesium is an **open project** and this is the time I can really put some efforts into making it as friendly as possible, keeping the core of the software as it was in the first release.

**Comment by AlanSP1** [comment]
@Lymphatus 

> This is my favorite approach, but it's a bit of a nightmare in terms of UX/UI. I'd like to keep a simple slider for casual users (they're a lot), implement the "desired image size" (which cannot be applied for PNGs) and give an "Advanced Mode" for fine tuning.
I just need to figure out how to make it usable UX/UI wise.

What I would suggest is tabbed interface. You already have many "windows" or "zones" where certain set of settings or info is placed. So, where you define how to compress images, use tabbed interface, name tabs "Simple", "Advanced" and "Image Size" (just suggestion) and that's it.

Today I think almost everyone knows what tabs are, what they do and with them you can easily switch between different modes of image compression (not sure if mode of compression is good term, but you know what I want to say).

It would work quite well in my opinion, you can make more than these three tabs (or change in different ones, I'm not insisting, just working with them for now), less, everyone would know what they do, and you have compression options in one place (i.e. window, i.e. zone).

Just to mention here shortly, how to make image comparison interface, [JPEG compressor](https://jpeg.compressor.software/) made that quite well, you can take a look how they made that. This part is very important when deciding how much to compress images, as too much of compression "destroys" images, but on the other hand, we want to compress them as much as we can (and yes, your algorithm is pretty powerful and gives great results, just to mention that, I'm impressed). You can download and test how they did their interface, and take some of ideas from that.
