### ISSUE TITLE
add shortcut for preview update make work faster 

### ISSUE THREAD

**Issue by wolfkingal2000** [Lymphatus/caesium-image-compressor#220]
add shortcut for preview update make work faster like refresh -F5  and can you add psd compressors ? thank

**Comment by Lymphatus** [comment]
I can add a shortcut for Preview (I'm thinking CTRL+P) but also remember, you can activate Auto Preview (View > Auto Preview) to have a preview of the image when you click it on the list.

For PSD compression: no, PSD is not an image format, it's a Photoshop file and holds a lot more info than a simple image.
