### ISSUE TITLE
Customizable MultiThread/hyperthreading Option

### ISSUE THREAD

**Issue by BlackGrimReaper** [Lymphatus/caesium-image-compressor#221]
**Is your feature request related to a problem? Please describe.**
 - I often compress batches of images, sometimes dealing with over 3000 images at once. To speed this up, I turn on the multithread option. However, this significantly slows my computer, making it tough to use for other tasks  at the same time which is given as its using all the available threads for processing.

**Describe the solution you'd like**
 - Having a customizable option to allocate the desired number of threads for compression in the settings would be highly beneficial. This way, I could designate 50% or 70% of the threads for compression, allowing me to continue working on other tasks while the compression process occurs in the background with nearly full power.

**Comment by Lymphatus** [comment]
Good suggestion. I can add an input that goes between 2 (min number for multithreading) and the guessed max threads (usually it's the number of physical cores of the CPU).
The multithreading checkbox was initially though for any kind of troubles with multithreding, but being able to customize it it's a good addition.
Thanks!

**Comment by Lymphatus** [comment]
Fixed in v2.5.1
