### ISSUE TITLE
Cannot exit the usage data window on MacOS

### ISSUE THREAD

**Issue by wideocean** [Lymphatus/caesium-image-compressor#223]
**Describe the bug**
If I open the usage data in the preferences dialog, the usage data window pops up but it is not possible to close the window anymore. There is no 'Close' button in the corner and it cannot be closed via 'Esc'. I had to completely force-quit the app.

**Software version**
2.5.0

**Operating System information**
 - OS: MacOS
 - Version: Ventura 13.5

**To Reproduce**
1. Go to preferences
2. Click on 'Show usage data'

**Expected behavior**
The usage data window pops up and can be closed again.

**Screenshots**
https://imgur.com/a/QtsA99i

**Comment by Lymphatus** [comment]
There's a exit button down below, but it's hidden since the window is too big. It should be smaller and scrollable.
As a temporary workaround while I fix it: you can press Enter and the window will close, because the exit button is immediately focused.

Thanks for the report!

**Comment by Lymphatus** [comment]
Fixed in v2.5.1
