### ISSUE TITLE
Photos larger than 400M cannot be selected

### ISSUE THREAD

**Issue by tomener** [Lymphatus/caesium-image-compressor#228]
**Describe the bug**
Photos larger than 400M cannot be selected.

**Software version**
v2.5.1

**Operating System information**
 - OS: Windows
 - Version 10

**To Reproduce**
1. Click on Open File
2. Select photos larger than 400M
3. The picture list window does not display selected photos

**Expected behavior**

**Screenshots**

**Application Log**
If you can, please provide your application log. The location of the file depends on your platform, but they usually are:
- Windows: C:/Users/USERNAME/AppData/Roaming/SaeraSoft/Caesium Image Compressor/caesium-yyyy-mm-dd.log
- macOS: /Users/USERNAME/Library/Application Support/SaeraSoft/Caesium Image Compressor/caesium-yyyy-mm-dd.log
- Linux: /home/USERNAME/.local/share/SaeraSoft/Caesium Image Compressor/caesium-yyyy-mm-dd.log

**Additional context**

**Comment by Lymphatus** [comment]
The software currently has a limit of 300Mb. I can increase it further - it was changed in the v2.4.1 release - but I'd like to run some tests to see if the app can really handle them.
Can you upload an example of a >400Mb image you are willing to compress, so I can make some tests?

**Comment by tehartos** [comment]
I need this feature too. I can upload a few images if you need some.

**Comment by Lymphatus** [comment]
@tehartos if you can, yes. If you have different formats would be awesome.

If the test succeed I will probably ship this change in the next release.

**Comment by SpacemanPete** [comment]
Is there a way I can help work on this feature update? 
I have JPGs and PNGs of lots of different sizes and I can make time for testing. 

This app has been able to handle larger files than any other compression software I've tried far (seriously, thanks so much btw for your work on this!) but unfortunately not large enough. I have some large PNG images (north of 380 MB) that I'm trying to compress to under 100MB so I can upload and submit to a printing service.

**Comment by Lymphatus** [comment]
Added in [v2.6.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.6.0).
