### ISSUE TITLE
App displays resizing percentage as pixels at next launch and forgets previous value

### ISSUE THREAD

**Issue by lrq3000** [Lymphatus/caesium-image-compressor#231]
**Describe the bug**
If user selects percentage resizing, then closes the app, then reopens it, the app remembers that resizing was set to percentage, but in the width and height values, the values shown are "px" instead of "%".

I did not test to see if this causes resizing to work on pixels instead of percentages, so I am unsure if this is just a display bug or a more severe image processing bug. /EDIT: this is only a display bug, the output is resized according to percentage, not pixels.

/EDIT2: This bug can also be reproduced by simply changing language, it is equivalent to restarting the app.

/EDIT3: In addition to misdisplaying the percentage as px, when restarting the app, it indeed forgets the previous resizing value.

**Software version**
2.5.1

**Operating System information**
 - OS: Windows
 - Version 11

**Screenshots**
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/1118942/5c713263-e2eb-460b-9d8b-287fafd06b23)

**Application Log**
[caesium-2023-09-22.log](https://github.com/Lymphatus/caesium-image-compressor/files/12699325/caesium-2023-09-22.log)

**Comment by Lymphatus** [comment]
It's actually a bug I got addressed in this commit https://github.com/Lymphatus/caesium-image-compressor/commit/f09ba954d23856e843e7aab6dd4dde27c2c8b823
Will be fixed on the next release. Thanks for reporting!

**Comment by azagthoth1** [comment]
I was going to report this one, but I'm glad it has already come to the attention of the developer. I really like this software, thanks for your hard work.

**Comment by azagthoth1** [comment]
> It's actually a bug I got addressed in this commit [f09ba95](https://github.com/Lymphatus/caesium-image-compressor/commit/f09ba954d23856e843e7aab6dd4dde27c2c8b823) Will be fixed on the next release. Thanks for reporting!

I was going to report this one, but I'm glad it has already come to your attention. I really like this software, thanks for your hard work.

**Comment by azagthoth1** [comment]
> It's actually a bug I got addressed in this commit [f09ba95](https://github.com/Lymphatus/caesium-image-compressor/commit/f09ba954d23856e843e7aab6dd4dde27c2c8b823) Will be fixed on the next release. Thanks for reporting!

I was about to report this one, but I'm glad it has already come to your attention twice. I really like this software, thanks for your hard work. Looking forward to the next release.

**Comment by Lymphatus** [comment]
Fixed in [v2.6.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.6.0).
