### ISSUE TITLE
Add option: Automatically open output folder or rename output files

### ISSUE THREAD

**Issue by lforlgg** [Lymphatus/caesium-image-compressor#232]
The compression effect is amazing, I love it too much.
It would be great if you could provide further options:
1. Automatically open the output folder after completion
2. Output to source folder, but automatically rename.
   like：xxx_Compressed.jpg
Thank you very much!
![add](https://github.com/Lymphatus/caesium-image-compressor/assets/105794681/29b05f4e-8042-408d-878b-1b3eedc6fd9c)

**Comment by lforlgg** [comment]
@Lymphatus
Thank you for your reply and guidance. 
I got it.
Thank you very much.

**Comment by BoxMiao007** [comment]
Can the recompressed file not replace the first compressed file and automatically add a numerical suffix, for example: image-Caesium-01.jpg

**Comment by Lymphatus** [comment]
Added in [v2.6.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.6.0)
