### ISSUE TITLE
Incorrect extension if file is not re-compressed

### ISSUE THREAD

**Issue by savchenko** [Lymphatus/caesium-image-compressor#234]
**Describe the bug**
With the option _"Skip if output size is bigger than the original"_ checked, the resulting file always has an extension selected in the _"Format"_ drop-down menu.

**Software version**
v2.5.1

**Operating System information**
 - Windows 10 22H2

**To Reproduce**
1. Set output file type to JPEG
2. Try to compress some vector which is obviously smaller in PNG
3. Observe original PNG being copied with JPEG extension into destination folder

**Expected behavior**
Keep original extension if file is unchanged.

**Screenshots**
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/300146/25ec7e07-58f2-4e9f-afe8-e2eedd98bdb0)

**Application Log**
```
[2023-10-08 00:27:38.328][I] ---- Starting application ----
[2023-10-08 00:27:38.329][I] UUID: "xxx-xxx-xxx-xxx-xxx"
[2023-10-08 00:27:38.485][I] Starting UI
[2023-10-08 00:28:17.328][I] Compression ended successfully.
Total images: 31 
Uncompressed size: "14.50 MB" 
Compressed size: "7.66 MB" 
Elapsed time: 1880 ms
```

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
do not open file

**Comment by V1e2n3k4a5t6e7s8w9a10r11l12u13** [comment]
closed
