### ISSUE TITLE
Maximum size in KB option and multiple Folders Compression and delete Files Permanently 

### ISSUE THREAD

**Issue by SamNeill** [Lymphatus/caesium-image-compressor#238]
Integrating a "Maximum Size in Kilobytes" feature, akin to online compressors such as Caesium, would enhance the functionality of our compression tool. Additionally, facilitating the simultaneous compression of multiple folders, as opposed to individually adding files from a single directory, would represent a significant improvement in user efficiency. These refinements aim to optimize user experience and provide a more comprehensive and user-friendly compression solution.
and delete files without moving to recycle bin

**Comment by Lymphatus** [comment]
The maximum size is an option introduced in the 2.5.0 release and works as the online compression does.

Caesium already allows you to open/drop an entire folder, with subfolders too. The only thing that is not supported is to select multiple folders to open at the same time, just one at the time. This is actually a limitation from some operating systems and not Caesium itself.

**Comment by Lymphatus** [comment]
Probably the size you entered is too low for the compression to work, so it leaves the file as it is. It's probably better if the application leaves a message in case this happens.

**Comment by Shailendra1703** [comment]
Tried this but it didn't worked as expected ! any suggestions ?

![image](https://github.com/Lymphatus/caesium-image-compressor/assets/84718204/6af8c8df-b749-4ce6-9666-4e300f6e6447)
