### ISSUE TITLE
FR: - "Save the sky" option - option to save big areas of relatively similar details - different compression setting for different image zones

### ISSUE THREAD

**Issue by AlanSP1** [Lymphatus/caesium-image-compressor#24]
With higher image compression (that works great on image zones with complex content, e.g. tree leafs, or lawn with flowers to name a few) sky can get "corrupted", or too compressed.

It would be great if we could choose different compression settings (or even better, if algorithm does that automatically) for different content "zones" to call them.

If overcompressed sky looks very bad, you don't even need to go and look at 1:1 (one pixel of image for one pixel shown on screen) to notice it. But, with same compression settings, you achieve great results with different content that has more "texture" to it.

If we could choose different compression settings for different content, or even better, that algorithm does that automatically, we would be able to achieve higher compression (i.e. smaller image sizes) and keep images to look "more decent" so to say.

Advanced JPEG Compressor has setting for something like this, but I think you could achieve even better results over them as your image compression algorithm is far superior, but at the moment it "fails" with sky and similar content. Sky is most noticeable area in images, relatively big area with similar colors and here algorithm goes "to the max", hoping to save space, but in same time it just goes a bit too far with that space saving.

If you could find some way to "save the sky", it would be really great, and images could be compressed even a bit more without looking too "washed out" in my opinion. Which would make your software even better.

**Comment by Lymphatus** [comment]
This is pretty interesting, but very unlikely to happen with Caesium. Advanced JPEG Compressor has more fine settings for each image it processes (if I remember correctly) but it's out of scope for Caesium.
There're a few AI based algorithms out there to achieve the result you want, but they are very very slow atm.
I'm closing this not because it's a bad request, I just don't see anything close to that in the near future.
PS: Giving a bit more compression options may mitigate the "sky issue".

**Comment by AlanSP1** [comment]
> PS: Giving a bit more compression options may mitigate the "sky issue".

I hope also that with a more compression options I would be able to achieve "good enough sky", with well compressed rest of image.

Also, hope that I might also give you some food for thought and you maybe (not insisting, nothing like that) get some idea how to achieve this.

And this is part in Advanced JPEG Compressor where you choose this options:

![](https://i.postimg.cc/DwVQd9qJ/JPEG-compressor.gif)

You would rise large parts to the max to "save the sky".
