### ISSUE TITLE
add only Width or Height in Resize and Keep aspect ratio

### ISSUE THREAD

**Issue by wolfkingal2000** [Lymphatus/caesium-image-compressor#240]
add only Width or Height in Resize and Keep aspect ratio

**Comment by wolfkingal2000** [comment]
> Duplicate of #164 The next release will support it

When will the new update be released?

**Comment by Lymphatus** [comment]
Added in [v2.6.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.6.0).
