### ISSUE TITLE
Automatically close after completion

### ISSUE THREAD

**Issue by awadrummer** [Lymphatus/caesium-image-compressor#242]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to have an option that automatically closes the program after it has completed compressing the files.

**Describe alternatives you've considered**

**Additional context**
I use a custom windows context menu to send multiple files to the software and they automatically start converting, but I have to close the window every time after the software has finished.

**Comment by Lymphatus** [comment]
Added in [v2.6.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.6.0)

**Comment by awadrummer** [comment]
@Lymphatus Awesome! Thank you so much!
