### ISSUE TITLE
Resize with max-width or max-height while keeping the ratio

### ISSUE THREAD

**Issue by ColinC5887** [Lymphatus/caesium-image-compressor#246]
The current version is not use-able at all. I'm still using the 1.7 version just because of this feature.
I do image resizing in batch. The images could be in any resolution. My requirement is clear: do compress and no image should be wider or higher than 2048PX.
The 1.7 version can achieve this by
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/47936374/3df7312d-03a6-472d-b9a3-eba0bb8ea1e7)

However, 2.X version can never make it.

**Comment by Lymphatus** [comment]
Duplicate of #164 
The next release will support it

**Comment by Lymphatus** [comment]
Added in [v2.6.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.6.0)
