### ISSUE TITLE
Carsh on `Corrupt JPEG data`

### ISSUE THREAD

**Issue by IITII** [Lymphatus/caesium-image-compressor#248]
**Is your feature request related to a problem? Please describe.**
current version will crash when handle `Corrupt JPEG data`.

**Describe the solution you'd like**
* catch execption and set to row msg
* give a btn to open logs dir directly 
* add logs dir to github readme.

**Describe alternatives you've considered**

**Additional context**

**Comment by Lymphatus** [comment]
I think it's fixed on [v2.6.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.6.0). The app should not crash anymore and just go ahead.
