### ISSUE TITLE
When adding a folder, add only specific file extensions to the list.

### ISSUE THREAD

**Issue by SysVR** [Lymphatus/caesium-image-compressor#251]
**Is your feature request related to a problem? Please describe.**
Use this if you want to process only certain files, etc.

**Describe the solution you'd like**
If you want to compress only jpg from a folder with multiple files, you may want to specify the file extension to read.

**Comment by Lymphatus** [comment]
I'm thinking of adding an option to perform an "Advanced Import" to customize a little bit the import process and allow for more advanced filters.

**Comment by SysVR** [comment]
thank you
