### ISSUE TITLE
Specify compression ratio

### ISSUE THREAD

**Issue by SysVR** [Lymphatus/caesium-image-compressor#252]
**Is your feature request related to a problem? Please describe.**
Unclear what compression ratio is being used.

**Describe the solution you'd like**
If this software uses oxipng, etc,
I don't know what the compression ratio is, so I would like to be able to specify the compression ratio.

**Describe alternatives you've considered**
Install a slider that allows you to specify the compression ratio for lossless compression.

**Comment by Lymphatus** [comment]
For oxipng, Caesium uses the preset level 3, and 6 as level for libdeflater. This is a snippet from libcaesium
```
oxipng_options = oxipng::Options::from_preset(3);
oxipng_options.deflate = Libdeflater { compression: 6 };
```

Setting this levels could be something I add in an "advanced" panel.

**Comment by SysVR** [comment]
thank you
