### ISSUE TITLE
TIFF files can't be added

### ISSUE THREAD

**Issue by savchenko** [Lymphatus/caesium-image-compressor#253]
**Describe the bug**
"Add folder" button does nothing when selecting a folder with TIFF files.

**Software version**
v2.6.0

**Operating System information**
Win 10 22H2

**To Reproduce**
1. Click on "Add folder" button
3. Navigate to a folder with `.TIFF` files
4. Click on the "Select folder" button

**Expected behavior**
Files are added to the processing queue.

**Screenshots**
N/A

**Application Log**
```
[2024-01-29 00:36:20.154][I] ---- Starting application ----
[2024-01-29 00:36:20.155][I] UUID: "c492e1a5-4374-4254-a216-f3cbde2dcf88"
[2024-01-29 00:36:20.304][I] Starting UI
```

**Additional context**
EXIF extract:
```
FileType                        : TIFF
FileTypeExtension               : tif
MIMEType                        : image/tiff
ExifByteOrder                   : Little-endian (Intel, II)
BitsPerSample                   : 8 8 8
Compression                     : Adobe Deflate
PhotometricInterpretation       : RGB
SampleFormat                    : Unsigned; Unsigned; Unsigned
ExifVersion                     : 0220
ComponentsConfiguration         : Y, Cb, Cr, -
CompressedBitsPerPixel          : 10
```

**Comment by SysVR** [comment]
supporting JPG, PNG and WebP formats onry.
