### ISSUE TITLE
Error: Cannot copy output file, check your permissions

### ISSUE THREAD

**Issue by fengziX** [Lymphatus/caesium-image-compressor#264]
**Describe the bug**
Error: Cannot copy output file, check your permissions

**Software version**
2.6.0

**Operating System information**
windows10   run as admin

**Screenshots**
![QQ截图20240305135342](https://github.com/Lymphatus/caesium-image-compressor/assets/25502192/48c9c0de-b1de-448e-b330-7efa3d05f256)

**Application Log**
[2024-03-05 13:55:09.620][C] Failed to copy from "C:/Users/Administrator/Desktop/002.jpg" to "C:/Users/Administrator/Desktop/002.jpg" (:0, )
[2024-03-05 13:55:09.628][I] Compression ended successfully.
Total images: 1 
Uncompressed size: "1.51 MB" 
Compressed size: "1.51 MB" 
Elapsed time: 5920 ms
[2024-03-05 13:55:12.139][I] Usage report sent successfully

**Comment by fengziX** [comment]
2.6.0 shows "Error: Cannot copy output file, check your permissions ", 
but use 2.5.1 compress the same files, it shows "Skipped: compressed file is bigger than original"

**Comment by Lymphatus** [comment]
I'm assuming is a problem related to #234 and its fix. I'll check it out.

**Comment by JeckPeppinger** [comment]
I had the same message for some images on ubuntu 23.10 and CIC v2.7.0

**Comment by JeckPeppinger** [comment]
hi, i checked and did not find a log or history that shows something useful. Will take care in the future and provide evidence if it happens again.

**Comment by fengziX** [comment]
> @JeckPeppinger 

It looks like it just outputs the wrong "error".

It should be "Error: Cannot copy output file, check your permissions ", not "Skipped: compressed file is bigger than original".

**Comment by JeckPeppinger** [comment]
![Screenshot from 2024-04-23 22-38-16](https://github.com/Lymphatus/caesium-image-compressor/assets/35139202/5be19722-75fb-45c6-a161-95a092a91a91)

captured the bug ... guess your hint that it should be the "skipped" message is correct.

**Comment by Lymphatus** [comment]
I was able to reproduce the bug and pushed a tentative fix. As you said, the message was wrong because the app was not really dealing with the extension change in filename. Should work as expected now and I'm gonna publish the fix on 2.7.0.
