### ISSUE TITLE
Add chroma subsampling option

### ISSUE THREAD

**Issue by Doofy420** [Lymphatus/caesium-image-compressor#266]
I'm trying to optimize a lof of images without losing too much quality and the ability to pick or disable chroma subsampling would be really useful. It seems that checking the lossless option is the only way to disable it atm.

**Comment by Lymphatus** [comment]
In the [core library](https://github.com/Lymphatus/libcaesium) there's an option to set Chroma Subsampling, it's just not exposed in the UI. With release 2.7.0 I'm adding a few "advanced" options for some formats, I might add this one too.
