### ISSUE TITLE
Concurrent compression?

### ISSUE THREAD

**Issue by douglasg14b** [Lymphatus/caesium-image-compressor#27]
Seeing if this has been considered. Had ~40,000 images to compress and was sad to see that this only utilized ~4% of my available processing power...

I regularly write concurrent processing tasks in my projects, though I work in C#, which makes it pretty easy to handle threads. This appears to be a task that is relatively simple to parallelize since it wouldn't have to worry much about contention on shared resources save for the UI? Then again, I know little about this project, it could be very difficult in the current codebase, spitballing.

**Comment by Lymphatus** [comment]
Old Caesium version was single-threaded indeed. In this new version I'm trying to achieve a full concurrent processing but I'm having a bit of trouble on Windows, while macOS works pretty fine. See #19. 
You can try the [alpha-2 release](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.0.0-alpha.2). Keep in mind it's an alpha version, use with care. Also, if you have issues opening the Windows version, look at #25 .
