### ISSUE TITLE
1366X768 laptop screen resolution, the software interface is not fully displayed

### ISSUE THREAD

**Issue by kofzhanganguo** [Lymphatus/caesium-image-compressor#274]
![Snipaste_2024-05-18_20-21-07](https://github.com/Lymphatus/caesium-image-compressor/assets/32073931/73a1a109-cd15-4937-8cfe-223fae679abe)
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/32073931/76c8f6d9-f98a-48a3-b1c6-b0b410c059b5)

The laptop screen resolution is 1366X768, so the software interface is not fully displayed. The button options at the bottom can only be displayed in full screen.

**Comment by Lymphatus** [comment]
If you collapse the compression options for every format, do something change? I think the but happens because the side panel is too big.

**Comment by kofzhanganguo** [comment]
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/32073931/b0718ecd-cb57-4899-b6d7-286da3c539c0)
Thanks for the author's answer, the method you mentioned can solve it.

**Comment by kofzhanganguo** [comment]
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/32073931/5c22bc93-d2c7-4867-a1e2-4dda6fc6966a)
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/32073931/5bbe0fe5-3146-419b-919f-18135b9df4a8)
The import exclusion file size of version 2.6 can be set to 4 digits, while version 2.7 can only select 2 digits. Exclusions or other options that exceed 2 digits cannot be selected

**Comment by Lymphatus** [comment]
@kofzhanganguo made another issue for this bug. If you find more please open a different issue so I can keep tracking of them. Thanks!
