### ISSUE TITLE
Advanced import enhancements

### ISSUE THREAD

**Issue by Lymphatus** [Lymphatus/caesium-image-compressor#275]
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/32073931/5c22bc93-d2c7-4867-a1e2-4dda6fc6966a)
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/32073931/5bbe0fe5-3146-419b-919f-18135b9df4a8)
The import exclusion file size of version 2.6 can be set to 4 digits, while version 2.7 can only select 2 digits. Exclusions or other options that exceed 2 digits cannot be selected

_Originally posted by @kofzhanganguo in https://github.com/Lymphatus/caesium-image-compressor/issues/274#issuecomment-2118810974_

**Comment by kofzhanganguo** [comment]
![CIBSG~GTF@X%LBHUCHX8~7G](https://github.com/Lymphatus/caesium-image-compressor/assets/32073931/2d96ba6d-a909-4a83-8fc0-62735be2d84c)
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/32073931/661ffbc4-b572-4e85-91ef-fdf7264a0435)
This advanced import method cannot be like the 2.6 version where you can drag and drop images directly into the software. You must click on the option to add files or folders. You cannot drag and drop folders into the software, which is very inconvenient. It is more convenient to drag and drop into the software like in the 2.6 version.
