### ISSUE TITLE
Can you explain little bit about how it works 

### ISSUE THREAD

**Issue by HakaishinShwet** [Lymphatus/caesium-image-compressor#278]
Just curious to know how compression with preserving quality will work and how effective it is compared to other similar solutions :-))

**Comment by Lymphatus** [comment]
If you want to have a bit more information you probably should look at https://github.com/Lymphatus/libcaesium, which is the library this tool is using.
About the compression, it really depends on the format. For example, for JPEG I'm using mozjpeg, so it can compare pretty much 1on1 with other tool using it (there might be small differences, but not that much). For PNG it's oxypng or zopfli. Diving a bit into the library is the key to discover more about the compression methods.
