### ISSUE TITLE
Recompress the failed image

### ISSUE THREAD

**Issue by 52linglong** [Lymphatus/caesium-image-compressor#282]
**Is your feature request related to a problem? Please describe.**

When I try to compress a large number of images in batch, over 10000 images, with 4 threads for parallel compression, a partial compression failure occurs. How do I recompress the failed image?

**Describe the solution you'd like**

The number is too large, the compression time is long, and only the failed images are compressed

**Describe alternatives you've considered**

- Clean: Clean up successful pictures and keep failed ones for easy compression.
- Compress: Compress only the previously failed image directly.

**Additional context**

- OS: Windows 10
- Software: 2.6.0

**Comment by Lymphatus** [comment]
Fixed in 2.8.0.
