### ISSUE TITLE
How to deploy the web version

### ISSUE THREAD

**Issue by yokebtc** [Lymphatus/caesium-image-compressor#283]

**Comment by Lymphatus** [comment]
This project is a desktop UI for the [libcaesium](https://github.com/Lymphatus/libcaesium) library, while the web version uses a WASM version of it, hosted on [libcaesium-wasm](https://github.com/Lymphatus/libcaesium-wasm). Unfortunately the WASM repo is not really documented, as it was mostly an experiment. You can ask question there tho.
