### ISSUE TITLE
Caesium always uses all available CPU threads, even when told not to

### ISSUE THREAD

**Issue by gdsa32** [Lymphatus/caesium-image-compressor#284]
**Describe the bug**
When processing a large batch of images, Caesium always uses all CPU threads available, even if we configure it to use only part of them. This causes the entire system to be irresponsive, even with a powerful CPU.

**Software version**
v2.7.1

**Operating System information**
 - OS: Windows
 - Version 11 23H2

**To Reproduce**
1. Open the Windows Task Manage and go to 'Performance > CPU'.
2. Click on the graph e choose 'Change graph to > Logic processors'.
3. Notice how the current running processes are using the CPU threads.
4. Open Caesium, go to 'Preferences' and change the Multithreading field to a value that is smaller than the total count of CPU threads in your system. In my case, I reduced from 16 to 12 threads.
5. Close the Preferences window.
6. Load a large batch of images in Caesium (say, 200 or more large images) and set a desired value for quality.
7. Make sure both Caesium and Task Manager are visible on your screen. Then click compress e observe the CPU use on the Task Manager. You'll notice all threads have 100% utilization, even if you configure it otherwise.

**Expected behavior**
Only the defined number of CPU threads should be used during compression.

**Screenshots**
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/39100541/addf1bc7-c563-4240-beaa-507067ed722f)

![image](https://github.com/Lymphatus/caesium-image-compressor/assets/39100541/eb8da898-5c8a-4966-8e63-0a0e61f0c22d)

**Application Log**
[caesium-2024-06-24.log](https://github.com/user-attachments/files/15960677/caesium-2024-06-24.log)

**Edit**
I added issue #285, asking for a new setting, allowing user defined priority for the Caesium process. This way, with process priority defined to 'below normal', for example, system will albeys be responsive, even when all CPU threads are used at 100%.

**Comment by gdsa32** [comment]
> I tested on my Windows 11 machine and seems to work as intended. There's a catch that maybe is what you are seeing: Caesium uses a pool of threads for processing the images, and when you set the number of threads, you tell how bit the pool is. This does not define which processors/threads are used in advance, but when it start processing a new image, chooses an available thread. If you define a number close to the max limit, by switching to different threads, it might seem that it's using every of them. Could you try with a lower value, like 4 out of 16 threads to see if gets better? For me the difference was really noticeable.

OK. I think I understand what you said. 

This is the CPU graph when I limit threads to 4:
![image](https://github.com/Lymphatus/caesium-image-compressor/assets/39100541/bbecdd9e-8f70-49c2-ab98-c58f52cdac06)

As you can see in the image, CPU threads do not look at 100% all the time and system responsiveness is a lot better. But obviously, processing time is much longer. 

So, I think the best approach here is implementing feature request #285, allowing a user defined process priority (I certainly will use 'below normal'). This way, Caesium can use all de processing power available, without negatively affecting system responsiveness.

**Comment by Lymphatus** [comment]
Closing this in favor of #285
