### ISSUE TITLE
Add an option to define custom process priority for Caesium

### ISSUE THREAD

**Issue by gdsa32** [Lymphatus/caesium-image-compressor#285]
**Is your feature request related to a problem? Please describe.**
This feature request is related to issue #284. As I describe in that issue, while processing a large batch of images, my system becomes irresponsive, because Caesium uses all CPU power available, even when I configure it to use a smaller number of CPU threads. 
If the image batch is really big and I want to continue to use my computer for other tasks while the images are being processed, I go to the Windows Taks Manager and manually reduce the priority for the Caesium process, thus making the system responsive again.

**Describe the solution you'd like**
My suggestion is to add an option in the Preferences windows, where we can set a desired 'Process priority' for the Caesium process, while processing images. A simple drop-down with the same priority options available in Task Manger: Real time | High | Above normal | Normal | Below Normal | Low.

**Describe alternatives you've considered**
Alternative is to set priority manually in Task Manager, each time we use Caesium.

**Comment by Lymphatus** [comment]
Fixed in 2.8.0.
