### ISSUE TITLE
[request] New size column

### ISSUE THREAD

**Issue by 3xploiton3** [Lymphatus/caesium-image-compressor#29]
![image](https://user-images.githubusercontent.com/19517680/86614844-cb6fc980-bfdd-11ea-926f-c9fedace14a4.png)

Request column : Original Size and New Size for compared

**Comment by Lymphatus** [comment]
I'm currently working on the `alpha-3` (just on local right now) to something related to that. I don't really like have too much columns to avoid having many numbers on screen. I'm thinking on a solution similar to this in the screenshot below.
<img width="1267" alt="Schermata 2020-07-07 alle 15 07 29" src="https://user-images.githubusercontent.com/12133996/86786226-0ae0f900-c064-11ea-94ed-008b30757391.png">

**Comment by 3xploiton3** [comment]
yeah, it's same function, i will waiting for the next release
