### ISSUE TITLE
Hope that the support for multithreading can exceed 64

### ISSUE THREAD

**Issue by shenyan-008** [Lymphatus/caesium-image-compressor#291]

**Comment by Lymphatus** [comment]
The limit for the multithreading option is what the software thinks are the maximum threads available. Usually it's equal to the cores of the CPU. More documentation [here](https://doc.qt.io/qt-6/qthread.html#idealThreadCount).

**Comment by shenyan-008** [comment]
Supplement: This is under Windows 10. I don't know C++. Is it possible to break this limit by having 64 threads in each pool and synchronizing 2 or more pools? My CPU has 96 cores and 192 threads.

**Comment by Lymphatus** [comment]
Sorry but it's not something that depends on Caesium, the detection is done by the Qt Framework and I'm not planning on changing how the number of CPUs are detected. In the attached documentation there're some edge cases described and they might apply to your specific case.
