### ISSUE TITLE
Caesium Image Compressor, trash, not accessible

### ISSUE THREAD

**Issue by aeast46** [Lymphatus/caesium-image-compressor#296]
Hi 

When I compressor a file on caesium, it compresses ok, but when I try to get back to original in trash, there is no trash in caesium, or nothing in my "windows trash bin" 

Can you advise where this is , or can this be fixed.

**Comment by Lymphatus** [comment]
There's an option to send the original files to trash.
Unless you are overwriting them all the original files stay in the original place.
<img width="350" alt="Screenshot 2024-08-16 122823" src="https://github.com/user-attachments/assets/f58bb565-bd28-436e-b607-afdea46a3cf8">

**Comment by aeast46** [comment]
Yes I have "to trash" setup the same as that, but where is the trash? where can i see the original , that was compressed? It definately doesnt list the original in the same location, it has just overwritten it to the smalled size, nothing else
Is it possible to get a recycle bin on the software?
Any idea how I can retrieve the original ? 
thanks

**Comment by Lymphatus** [comment]
The file is moved to the system trash, regardless of the operating system you are in.
If this is not working for you I need more info, like the options you are using in the `Output` panel.

**Comment by aeast46** [comment]
Please see attached - definately not in my system trash, it looks like a bug in the software.
![Caesium issue](https://github.com/user-attachments/assets/55727a0d-ea06-40e7-a3d9-97aec8e1f920)

**Comment by Lymphatus** [comment]
I tried to reproduce the same scenario but seems working for me. The only thing that comes to my mind is that you might be compressing the picture on a OneDrive folder and that might not support moving files to trash, but I tried on my OneDrive folder and seems to be working fine.

**Comment by aeast46** [comment]
Checked one drive not there, is it possible to put an actual trash bin in the software would make it alot easier, thanks

**Comment by aeast46** [comment]
Matteo, is it possible to put a recycle bin in the software?

Thanks
Anthony

**Comment by aeast46** [comment]
Hi Matteo

can you assist any further with this?

thanks
Anthony

**Comment by aeast46** [comment]
Is it possible to have a recycle bin in the software? please advise either way , thanks Anthony

**Comment by aeast46** [comment]
I tested it out on one drive, and it seems to send them into the recycle bin when there in one drive, but it doesnt work on windows explorer , do you know why? Windows 11
Thanks

**Comment by nrothwell** [comment]
is the setting saved to a config file like .ini. where is the config saved

**Comment by Lymphatus** [comment]
I do not plan on adding a dedicated trash for the application. Yours might be a bug or you might be using a drive that does not support moving files to the trash.
The only thing I can improve is the feedback when the application fails on moving files to the system trash.

**Comment by nrothwell** [comment]
> I do not plan on adding a dedicated trash for the application. Yours might be a bug or you might be using a drive that does not support moving files to the trash. The only thing I can improve is the feedback when the application fails on moving files to the system trash.

The Drive is OneDrive, does the app support OneDrive and also does the app supports config file whereby it saves all the setting in one INI file so make it easy to setup devices with automation 

thanks a mill

**Comment by Robbo1234** [comment]
Caesium Image Compressor works on files or folders from your local C: drive or OneDrive, but it doesn't work on files or folders located on an external server drive. Can this be fixed?

**Comment by Lymphatus** [comment]
@Robbo1234 by saying "but it doesn't work" you mean moving the originals to the trash or it's another kind of issue? If the latter, please open a new issue and provide as much info as possible to reproduce the problem. Thanks.

**Comment by Robbo1234** [comment]
This issue @Lymphatus is related to moving the originals to the trash (the users Recycle Bin).

**Comment by nrothwell** [comment]
@Lymphatus I tested it again, as the image file is stored on a UCN Path (Network Share), when it deletes the original file, the file is unrecoverable because there is no network share recycle bin on Windows 

Would it be possible to add a redirect to the local recycle bin, or a custom folder i.e C:\Users\%username%\Pictures/Bin

thanks

**Comment by Robbo1234** [comment]
@Lymphatus maybe you could add a new folder deletion section, allowing users to control where the originals are trashed after compression. Thanks
![image](https://github.com/user-attachments/assets/ef1bec95-e313-4092-ba6e-636321b629a1)

**Comment by Lymphatus** [comment]
Right now I do not plan on adding a separate "Caesium trash" to move files in if the system one is not available. I might add some more feedback for when the app fails to move to the OS trash tho.

**Comment by nrothwell** [comment]
@Lymphatus so currently the app does not support Mapped drives on a Domain.  Do we need to request a new feature.

**Comment by aeast46** [comment]
@Lymphatus , I am having the same issue, can this feature be added ?thanks

**Comment by Lymphatus** [comment]
Supporting trashing on drives that don't use the system trash - like network drives - is not planned right now. As workaround, you can compress on another folder or with a suffix and then delete the original yourself.

**Comment by aeast46** [comment]
Matteo, just checking is your email address info@saerasoft.com

**Comment by aeast46** [comment]
Hi Matteo, please see attached, can you resolve this on the software, its just not moving to trash

Would you interested in having a chat outside of github? 

Thanks
![Issue with Caesium Software 11 31](https://github.com/user-attachments/assets/3d0ef396-977c-4192-820b-7e128dfa5057)

**Comment by aeast46** [comment]
See in the info section

**Comment by Lymphatus** [comment]
The issue is closed as a "won't fix". Please stop commenting on this.

**Comment by aeast46** [comment]
Hi Matteo, Can I get your email address , Im looking to discuss making a donation. Im emailing from my company. Please provide email address/phone number to discuss further
Thanks
Anthony
