### ISSUE TITLE
Is it possible to disable progressive mode for JPG output?

### ISSUE THREAD

**Issue by wrzlpete** [Lymphatus/caesium-image-compressor#299]
An Image (5504 w x 8256 h) converted via caesium throws an error / doesn't display when trying to view from a media server (Fritz box) to an LG TV via its integrated Media Player app. The original image works, and the original image converted via RIOT works aswell. 

The only explanation I could find is that caesium seems to force JPEG in progessive mode, which seems to be causing this: non progressive mode JPEGs seem to always work, where as some of the progressive pictures do not (portrait at least).

Can progressive mode be disabled in caesium gui?

Thanks for your time!

**Comment by Lymphatus** [comment]
Added an option in 61459d92b33fa3c281bccfe14844369108114888 to disable progressive JPEG compression.

**Comment by Lymphatus** [comment]
Fixed in 2.8.0.
