### ISSUE TITLE
Development status?

### ISSUE THREAD

**Issue by LeBaux** [Lymphatus/caesium-image-compressor#3]
I don't want to be that guy, but there is no news for some time here or social media. Could you please share some updates? Thanks!

**Comment by Lymphatus** [comment]
I'm sorry for the lack of news about the project! It's true I'm not pushing anything into this repo or social media, but I'm still working on this. The problem I had with the current version was a bit overwhelming and made me to a (almost) total code rewrite - which you all can't see yet.

I'm also into some UI enhancement which needs some work too.

Thanks for the interest - and for being **that** guy. I promise that I'll be more clear about the development in the future.

**Comment by LeBaux** [comment]
Thank you for the update, I think more people will be glad to see this project is still in the works  ❤️ Just today I decided I might want to finally my trusty [JPEG Resampler 2010](http://software.macek.cc/resampler2010.php), I tried probably 15 pieces of software and I have to say, caesium offers the best workflow in terms of batch editing. One thing I like about RIOT is "Compress to size" function, that's straight up idiotproof function for technically impaired. BUT I don't want to halt you with feature request while core app needs your attention. 🤐 Also, I am windows pleb, so I would love to see beta complied for win. Screenshot here on github looks gorgeous, so I added it to [caesium alternativeto page](https://alternativeto.net/software/caesium/)). I believe good portion of traffic and attention might come from there. OK, I shut up now, thanks again for the good news!

**Comment by WPFilmmaker** [comment]
I am glad to see the development has not stopped! @Lymphatus Thank you for you work!

**Comment by Lymphatus** [comment]
Just want to share a quick update on this topic.
Right now I'm unable to keep the development going due to the fact my working laptop is now gone. I'm replacing it but it's a bit expensive and needs some time.

I apologize for this, I'll try to get back to work as soon as possible.

**Comment by 3xploiton3** [comment]
> Just want to share a quick update on this topic.
> Right now I'm unable to keep the development going due to the fact my working laptop is now gone. I'm replacing it but it's a bit expensive and needs some time.
> 
> I apologize for this, I'll try to get back to work as soon as possible.

don't forget to backup in the cloud 😉

**Comment by Lymphatus** [comment]
Another quick update: it's been a long time (almost 2 years!) since I wrote something about the development status, so here I am.

Well, in the last couple of weeks I've been working on the project and it's almost ready for a very early _alpha_ release.
I'm calling it _alpha_ just because some of the previous features (eg. the resize) are lacking right now - they will be added quite soon - but the core it's working.

**Comment by 1024mb** [comment]
> 
> 
> Another quick update: it's been a long time (almost 2 years!) since I wrote something about the development status, so here I am.
> 
> Well, in the last couple of weeks I've been working on the project and it's almost ready for a very early _alpha_ release.
> I'm calling it _alpha_ just because some of the previous features (eg. the resize) are lacking right now - they will be added quite soon - but the core it's working.

Thanks for your work. One question, I know the current version is alpha so my question is, would the GUI get rework in the future or the current one is the one that will stay with no plans to change it? I really liked the v1 GUI.

**Comment by Lymphatus** [comment]
@1024mb I'd like not to change much from the alpha-2 UI for the next releases. If you want to discuss the UI just add another issue, we can talk about that in there.
