### ISSUE TITLE
The font is changed to ugly "Simsun", but 2.7.0 and 2.7.1 font was good.

### ISSUE THREAD

**Issue by suyangzuo** [Lymphatus/caesium-image-compressor#311]
The screenshots below is all 2.8.0

![菜单](https://github.com/user-attachments/assets/4802fb7e-9901-4562-8d1d-15180457339e)
![选项](https://github.com/user-attachments/assets/3fb5f387-9704-4198-90e3-1f4e7a85a381)
![压缩选项](https://github.com/user-attachments/assets/c581d4de-7ef4-4838-8c23-16ccd7f05951)

**Comment by Lymphatus** [comment]
Version 2.8.0 comes with the standard font of Qt 6.8.0, I did not manually changed it. I can try change it, but I must change it with a system font. Do you have any suggestions?

**Comment by suyangzuo** [comment]
> Version 2.8.0 comes with the standard font of Qt 6.8.0, I did not manually changed it. I can try change it, but I must change it with a system font. Do you have any suggestions?

I suggestion "Microsoft Yahei" as it's included by default by windows.

**Comment by Lymphatus** [comment]
Happens to be a bug with Qt 6.8.0 ([reference](https://bugreports.qt.io/browse/QTBUG-129832)).
I pushed a fix that will ship with the next release.
If you want, you can apply a temporary fix by putting a file in the Caesium installation/executable folder (where the "Caesium Image Compressor.exe" file is located).
Create a file named `qt.conf` and put this inside:
```
[Platforms]
WindowsArguments = fontengine=gdi
```
Next time you open the application it should use the old font.
Remember to delete this file when the next release will come.

**Comment by Lymphatus** [comment]
Released 2.8.1.
