### ISSUE TITLE
Force light mode

### ISSUE THREAD

**Issue by vivadavid** [Lymphatus/caesium-image-compressor#312]
Hi,

Starting with version 2.8.0, Caesium applies dark or light mode depending on your Windows settings.

Personally, I prefer having Windows in dark mode, while having most of my programmes in light mode. Would it be possible to force light mode (or dark mode) regarless your Windows settings?

Thanks!

**Comment by Lymphatus** [comment]
Somehow Qt (Caesium is using 6.8.0) makes it difficult to force a specific theme when the system has another. The only solutions I found so far involved creating custom color schemes based on the default ones, but by doing so things can break really quickly. I'll do some more research, but for now I think it's not possibile.

**Comment by vivadavid** [comment]
They had a similar in qBittorrent. If it's too complicated, don't worry about it:

https://github.com/qbittorrent/qBittorrent/issues/21421

**Comment by Lymphatus** [comment]
So, [this comment](https://github.com/qbittorrent/qBittorrent/issues/21421#issuecomment-2399383300) got me on track to solve the issue. Since I'm using Qt 6.8.0, there's a way to force a theme. Pushing a commit right now to support that feature.

**Comment by vivadavid** [comment]
Thanks! :-)

**Comment by vivadavid** [comment]
My pleasure. Thank you! I'll try it with the next release.

**Comment by Lymphatus** [comment]
Released 2.8.1.

**Comment by vivadavid** [comment]
It works! Thanks again, especially for being so quick!
