### ISSUE TITLE
Add option to enable 'Keep Aspect Ratio' when resizing using dimensions

### ISSUE THREAD

**Issue by RafidMuhymin** [Lymphatus/caesium-image-compressor#32]
When I try to resize an image using dimensions the 'Keep Aspect Ratio' option gets greyed out. But it's more convenient than using percentages. So, please add the option to enable it as we can do in windows photos or any other photo resizers.

**Comment by Lymphatus** [comment]
You can use the `Short Edge` and `Long Edge` options while resizing. They will keep the aspect ratio.
