### ISSUE TITLE
Resizing not working correctly in 2.8.2

### ISSUE THREAD

**Issue by michaelbruetsch** [Lymphatus/caesium-image-compressor#320]
Hi there,

Maybe you are already aware of this bug, but here we go, it's pretty simple: The "Resize" feature isn't working correctly in version 2.8.2. For example: I selected "Resize to fit - Long edge" with 3400px and activated the checkbox "Do not enlarge". My 3024x4032px image is then resized (and enlarged) to 3400x4533px.

I downloaded version 2.7.1 and there it works as expected: The image is resized to 2550x3400px.

But beside that, really great image compressor! Really fast and easy to use and I don't have to use 2 different tools for PNG and JPG anymore :-)

Best regards,
Michael

**Comment by Lymphatus** [comment]
Are you selecting the "Keep Metadata" checkbox? It can affect the resizing if the image has rotation info in EXIF.

**Comment by michaelbruetsch** [comment]
Yes I did, good to know, thanks!
