### ISSUE TITLE
Is it posible to convert one image into multiple sizes and resize without encoding?

### ISSUE THREAD

**Issue by tomasts248** [Lymphatus/caesium-image-compressor#34]
Something like:
1. Input:
Image1, Image2
2. Output:
Image1x350px ,Image1x768px , Image1x1024px, Image1x2048px, Image2x350px, Image2x768px, Image2x1024px, Image2x2048px
Which would be useful for creating responsive versions of an image for web dev for static webs.

**Comment by Lymphatus** [comment]
I don't think this will ever be implemented. It's a useful feature, but it's quite out of the scope of this tool, which is a compressor. There's a resize option, but it's just an handy utility to further reduce the image size. What you are describing is more like a feature for a specialized image resizer.

**Comment by tomasts248** [comment]
Oh I see, thank you for explaining, may I ask if you happen to know another tool that could do this?

**Comment by Lymphatus** [comment]
Honestly, I don't really know. If I had to create a set of thumbs, I would just create a quick script to do that server side. But it's not a solution for everyone.

Closing this since it's not related to Caesium anymore.
