### ISSUE TITLE
Changing defaults of the first launch

### ISSUE THREAD

**Issue by maxim-uvarov** [Lymphatus/caesium-image-compressor#37]
Hey! Thanks for the awesome app

I suggest to use this settings as more user friendly (IMHO):
![image](https://user-images.githubusercontent.com/4896754/97700416-5cfbcd80-1ade-11eb-8ace-c4aa6d4d5a74.png)

Feel free to ignore:)

**Comment by Lymphatus** [comment]
This is a good advice. I shall take a look at default options in general, since right now they are _undefined_
