### ISSUE TITLE
Caesium 1.7.0: Keep original date information fails when overwriting

### ISSUE THREAD

**Issue by chocolatechipcats** [Lymphatus/caesium-image-compressor#42]
I didn't see "Keep original date information" in alpha 3, so I assume it hasn't been implemented yet. When it is implemented, here's an oversight I discovered from 1.7.0 that could hopefully be corrected:

When "Keep the original Date information" is selected in options and the compressed image overwrites the original ("Same folder as input", same format, no suffix), the timestamps of the overwritten file change. 

Thank you.

**Comment by chocolatechipcats** [comment]
Mostly for confirmation, has this feature been dropped in the new version?

**Comment by Lymphatus** [comment]
No, it's just not implemented yet.

**Comment by chocolatechipcats** [comment]
Thank you. Mind sending a message here when it is? It's a feature I use a lot.

**Comment by Lymphatus** [comment]
Sure. I'll re-open the issue, I will close it again when implemented. I'll also write a note here.
