### ISSUE TITLE
[URGENT] Instead of freeing up space, it is consuming more.

### ISSUE THREAD

**Issue by rogerhnn** [Lymphatus/caesium-image-compressor#44]
**Caesium v.2.0.0 alpha 3**
When converting instead of freeing space I am losing space in my hard drive.

Example:
Free space on hard drive before converting 150 jpg images (1gb size, about 6k pixels each): **6gb**
After converting all the images: **5gb**

The images were smaller, after conversion, instead of 1gb they were down to 19,7mb.
But somehow I lost 1gb in space in my hard drive.

Tried to replicate this problem with Caesium 1.7.0 it didn't happen, it's converting and freeing the space.

Tried this multiple times, and lost some GB in the process.
It's a known bug?

**Comment by Lymphatus** [comment]
This might be something related to the compression options you set. Can you provide me a screenshot of which Output options did you choose?

Possibile explanation: the new Caesium uses temporary folders to store images while compressing. Maybe they were not freed after compression, resulting in more space used. Check out 
`C:/Users/<USER>/AppData/Local/Temp`
if there are Caesium related files in there.

**Comment by rogerhnn** [comment]
Sure, this is what I am using:
![image](https://user-images.githubusercontent.com/1373782/104113099-193ef480-52d5-11eb-8690-11e58d972a66.png)
Basically, 80 quality and resize to fit 1920px long edge.

It's strange because I am not using images which are stored in C drive, I have 6 hard drives, tested this with 2, which are not my C drive, and both had same issue. I don't have a temp folder on the drives that I am converting the images.
And in C drive I only have the tmplst file with 0kb size.

**Comment by Lymphatus** [comment]
I run a few tests (on OS X, bu should apply to Window too) to find out the "issue".
When you overwrite your files by selecting "Same folder as input" Caesium moves the old files to the Recycler Bin/Trash for added security in case something goes wrong and you want to revert it back. Simply by emptying the Recycler Bin you should see you gained space.

This is a feature I silently added to the 2.0.0 version and it's planned to be a feature you can turn off/on in preferences.
Let me know!

**Comment by rogerhnn** [comment]
Thank you!
That was the "issue", also my mistake for not checking the Recycle Bin, sorry for that.
I am so used to use shift+delete when I want to delete something that I rarely check the trash.
After emptying the trash everything returned to normal.

My suggestion would be a toggle to select if you want to permanent delete the files, or just move them to the trash like it is right now.

- [x] Same folder as input
- [ ] Permanent delete files instead of moving them to the trash.

Thanks again!

**Comment by Lymphatus** [comment]
I'll probably add a checkbox like you suggested in a dedicated Preference panel (which is missing in the current build) along with other options I'm planning to add/insert back from v1.

Closing this since it's not an issue anymore and will eventually implement the suggestion in future builds.
Thanks for the feedback!
