### ISSUE TITLE
"Do not enlarge" not working

### ISSUE THREAD

**Issue by mi1escr0we** [Lymphatus/caesium-image-compressor#45]
Love Caesium but the "do not enlarge" option seems not working.
System: Win 10 Workstation ; Caesium Image Compressor : v2.0.0-alpha.3

**Comment by Lymphatus** [comment]
Hi! Can you provide me an example, so I try to reproduce? Which is the original resolution of the image and which options are you selecting? Thanks!

**Comment by mi1escr0we** [comment]
> Hi! Can you provide me an example, so I try to reproduce? Which is the original resolution of the image and which options are you selecting? Thanks!

Yep there is a screenshot of it , the original images were like "1440*1080" or "1887*1080", with "do not enlarge" option selected, the outputs just got bigger , both resolution and size 😃 
![image](https://user-images.githubusercontent.com/30818046/104980517-adc9f500-5a41-11eb-9f72-9371be8675be.png)

**Comment by Lymphatus** [comment]
Definitely a bug for the short/long edge options. Pushed a fix on 959137cbcccb0fe6eb5368597cf5890ae1996818, should be ok in the next release
