### ISSUE TITLE
文件压缩有的图片还比之前变的大了，希望解决

### ISSUE THREAD

**Issue by vicentory** [Lymphatus/caesium-image-compressor#46]
![image](https://user-images.githubusercontent.com/10493597/105284130-c4f91600-5bec-11eb-93ea-a059dc054084.png)
文件压缩有的图片还比之前变的大了，希望解决；
还有就是打开来源文件夹时打开的是安装目录，安装的软件是便携版。

**Comment by wordlesswind** [comment]
这里是 Caesium Image Compressor V2 的 Repo，有关压缩率的问题，也许你应该在 [libcaesium](https://github.com/Lymphatus/libcaesium) 反馈。
同样的，#47 是对于 V1 而言的，请不要在本 Repo 反馈。

Here is the Repo of Caesium Image Compressor V2. Regarding the compression ratio, maybe you should report it in [libcaesium](https://github.com/Lymphatus/libcaesium).
Similarly, #47 is for V1, please do not post in this Repo.

**Comment by xzkeee** [comment]
个别图片是会这样,  图片纹理多的情况下  大小按设置的质量是会比原图高
很正常的
