### ISSUE TITLE
Simplified Chinese is not displayed completely in the language setting

### ISSUE THREAD

**Issue by vicentory** [Lymphatus/caesium-image-compressor#47]
Simplified Chinese in the language setting is incomplete, I hope it can be optimized, thank you. If necessary, I can set the simplified language. But I didn't see how to set the language in the source code.
语言设置里简体中文显示不完整，希望能优化一下，谢谢。如果需要我可以来设置简体语言。但是我在源代码里没有看到如何设置语言。

**Comment by Lymphatus** [comment]
Chinese translation for version 1.7 is not complete. For version 2 it'll be refreshed and updated hopefully.
