### ISSUE TITLE
Downloading updates over plain HTTP

### ISSUE THREAD

**Issue by jwagner** [Lymphatus/caesium-image-compressor#5]
I'm not up to date on QT, windows or C++ development, so if I'm being ignorant, please forgive me.

From having a quick look at the [source code](https://github.com/Lymphatus/caesium-image-compressor/blob/master/updater/src/updater.cpp#L13) it looks like you are downloading updates over plain HTTP. This would mean that it's trivial to hijack the computers of users of this software.

I would recommend to at very least use HTTPS with proper certificate validation for downloading updates.

**Comment by Lymphatus** [comment]
Yes, that's true. I will address this issue as soon as the updater gets ready, since right now it's just a skeleton of what it will/should be.
