### ISSUE TITLE
Possible Bug: Failure to Process on Mapped Network Drives

### ISSUE THREAD

**Issue by Saijin-Naib** [Lymphatus/caesium-image-compressor#51]
Caesium seems to be unable to work with any data that are not local, such as mapped network drives from my NAS.

The drive is hosted by OpenWRT, has NTFS underlying it, and is using SMB v3. Full read/write permissions are granted to any users on my local network. Other programs can work with these mounted drives just fine.

**Comment by Lymphatus** [comment]
Hi! Just to clarify, which version are we talking about?

**Comment by Saijin-Naib** [comment]
V2.0.0-alpha3 on Windows 10 host

**Comment by Saijin-Naib** [comment]
Seems to be resolved as of V2.0.0-alpha5. Not sure what commits fixed this.
