### ISSUE TITLE
Image quality still heavily discolored

### ISSUE THREAD

**Issue by chicagolandcoders** [Lymphatus/caesium-image-compressor#52]
Using any form of Jpeg compression creates significant discoloration in both caesium 1.7 and 2.0. Lossless, fast, only resize. 

https://files.slack.com/files-pri/TJT9B05GR-F01UBP0KKMK/image.jpeg
https://files.slack.com/files-pri/TJT9B05GR-F01UBP15HHT/image2.jpeg

**Comment by Lymphatus** [comment]
(I cannot see the images without logging into Slack)

I guess it's a color profile issue. Does this thing happen with the Keep Metadata checkbox checked?

**Comment by chicagolandcoders** [comment]
After digging. The photos used the Prophets RGB profile which is known to be primarily for print and browsers tend discolor it as well. That being said the side by side comparison of input and output photos is still drastic enough to be an issue. 

![Screenshot_20210416-102643_Slack.jpg](https://user-images.githubusercontent.com/37384693/115047696-61565000-9e9e-11eb-9dac-b381b8b54713.jpg)

**Comment by chicagolandcoders** [comment]
It seems like keep metadata prevents the issue. Convert to Srgb would be an insanely handy feature.

![test face-prophoto rgb ](https://user-images.githubusercontent.com/37384693/115048827-9fa03f00-9e9f-11eb-9268-1e850c57e057.jpg)

**Comment by joaopedrofrech** [comment]
I'm having the same issue and found this post while looking for answers. 

When uncheck the "keep Metadata" box, the color profile conversion for sRGB doesn't happen and the colors don't change.

However, using other tools to convert the color profile don't change the colors like caesium does, so it looks like a conversion problem.

Then the image is already on sRGB, it ok, but when we need to convert, caesium kills the colors.
