### ISSUE TITLE
Beta 4: Advanced mode button doesn't change when switching between easy/advanced mode

### ISSUE THREAD

**Issue by masterrite** [Lymphatus/caesium-image-compressor#55]
A small issue - just thought you should know.

![Snipaste_2021-05-01_12-31-25](https://user-images.githubusercontent.com/20837366/116791672-3f052a80-aa79-11eb-8883-b995df809dbe.png)
![Snipaste_2021-05-01_12-31-34](https://user-images.githubusercontent.com/20837366/116791673-3f9dc100-aa79-11eb-9769-a0fb8a28525e.png)

Also, I did a quick side-by-side comparison between 1.7.0 and 2.0.0 beta 4, both with 98% quality using jpg. It seems that 2.0.0 gives a bigger file size (13.8mb vs 12.9mb) but gives better quality, especially at the edges of in-photo objects. I think I'll switch to 2.0.0 from here on. Thanks for all your work!

**Comment by Lymphatus** [comment]
The algorithm powering the two versions is very different, so this kind of results is expected. You can probably lower the quality on v2.0 reducing the size of the output and the quality should be better overall.

**Comment by Lymphatus** [comment]
Layout changed on alpha.5, so I can now close this.
