### ISSUE TITLE
Can only compress if the resize option is checked (v2.0.0-alpha.4)

### ISSUE THREAD

**Issue by topfuel75** [Lymphatus/caesium-image-compressor#56]
Im testing v2.0.0-alpha.4 on a Windows 10 machine. I guess I have the latest update.

It seems to only preform a compress if "Resize" is checked and I actually do a resize. 
I tried to set "Rezize to fit" to "Percentage" and "Width:" and "Height" to 100%. But that did not work. No compressed image in the selected folder and a red dot in the image list indicating that the image wasn't compressed.

If do an actual resize of the image, then the image gets compressed. There a compressed image in the selected folder and a green dot in the image list indicated everything went fine.

I have only tried with jpeg so far.

**Comment by Lymphatus** [comment]
Can you please provide a screenshot of the options you are using while facing the problem? There might be other - less obvious - options that cause the bug. Thanks!

**Comment by topfuel75** [comment]
Absolutely!
Each screenshot is taken right after hitting the Compress-button. So you can see which settings resulted in a successful compression.

![01](https://user-images.githubusercontent.com/3333119/119044840-fdeaa100-b9ba-11eb-9e84-67891180e858.PNG)
![02](https://user-images.githubusercontent.com/3333119/119044867-03e08200-b9bb-11eb-9741-7914bf4f078b.PNG)
![03](https://user-images.githubusercontent.com/3333119/119044890-0cd15380-b9bb-11eb-8aed-b408969fbd08.PNG)
![04](https://user-images.githubusercontent.com/3333119/119044906-10fd7100-b9bb-11eb-8fa7-dbc1583fbc60.PNG)

**Comment by Lymphatus** [comment]
Just one more question, since I'm not able to reproduce it, at least on OS X: the destination files already exists? Maybe the software is trying to overwrite them and fails. The reason the why the resize option "works" is that it creates a temp file first, do the processing and then move the processed file in place.

I'm gonna test on Win too just to be sure it's (or not) platform related.

**Comment by topfuel75** [comment]
I might found out why you can't reproduce the issue. 
I have installed Caesium on disk E:
Win10 is installed on disk C:
On the screenshots above I tried to compress images that were located on disk H:

I copied the images and past them into disc C: and disk E: (both worked fine).
Then I compressed the images from their new location.
And that worked like a charm.
