### ISSUE TITLE
EXIF data not copied from original

### ISSUE THREAD

**Issue by casey314** [Lymphatus/caesium-image-compressor#59]
Windows 10
Version 2.0.0-alpha.4, Advanced Mode,, Keep Metadata=Ticked, Do Not Enlarge=Un-ticked, Resize 50%, Quality 27.
The compression is fast and produces small file sizes but does not copy EXIF data from the original jpeg file.
The program was run as 'Administrator' to convert files on an external USB drive into the same folder with a suffix added to the compressed filename.
Version 1.7.0 compresses and keeps the EXIF data for the same files if 'Skip if the output size is greater than the original' = Un-ticked.

**Comment by smresultwithout** [comment]
I've the same issue.

**Comment by Lymphatus** [comment]
Gonna take a look and eventually fix in the next release. Thanks!

**Comment by Lymphatus** [comment]
Fixed on alpha.5
