### ISSUE TITLE
Missing libstdc++-6.dll in windows alpha 5 pre release.

### ISSUE THREAD

**Issue by NULL0B** [Lymphatus/caesium-image-compressor#63]
Hello, I thik this can be solved linking statically.
Greetings

**Comment by chocolatechipcats** [comment]
I can confirm this. There's also a few other libraries missing. I was able to copy most of them from the alpha 4 release though.

**Comment by Lymphatus** [comment]
Yeah, some .dll where missing. I fixed the release package, you should be able to run it if you download it again.
