### ISSUE TITLE
Cant compress images in non-English directory

### ISSUE THREAD

**Issue by absentmemory** [Lymphatus/caesium-image-compressor#65]
Only files whose directories are in English can be compressed, if there are non-English words in the directories, they cannot be compressed

**Comment by Lymphatus** [comment]
Hi! Which Caesium version and platform are you using?

**Comment by absentmemory** [comment]
2.0.0 alpha.5 and alpha.4 both have this error.

**Comment by Lymphatus** [comment]
I'm trying to reproduce the problem using Japanese and umlauts characters for testing (as for #53), but seems to work pretty well. Alpha.5, Windows 10 with Beta Unicode support disabled and Italian as system language.

Can you provide me the folder names/characters giving you issues?

**Comment by absentmemory** [comment]
The folder is Chinese characters like "压缩测试"、"论食用水水质解决方案",and I have tried some other Chinese folder name , caesium didn't work either. The folder structure is C:\Users\*\Desktop\压缩测试\论食用水水质解决方案 .  

Thanks for your work.

**Comment by Lymphatus** [comment]
Just tried to compress some files with the same folder names you provided, but seemed to work fine. If you just use English characters does it work? Also, the files you are trying to compress are in the same drive (C:\ for example) or on different/external/network drives?
Also, if you can, can you provide a screenshot of the compression/resize/output options? So i can try to be as close as I can trying to reproduce the issue.

Thanks for you contribute!

**Comment by absentmemory** [comment]
When I use English characters or number to name the folder, caesium works smoothly. If the name of folder(s) or file(s) have any Chinese characters ,it doesnt work.
These files are all in same drive.And a screenshot is attached bellow.Pathname is "C:\Users\gamer\Desktop\1".
Thanks for your reply!

![Snipaste_2021-08-03_19-30-02](https://user-images.githubusercontent.com/63712588/128008152-b9146916-9fba-44cc-a73c-a53d1530d79a.png)

**Comment by Lymphatus** [comment]
I guess it happens with the alpha.5 too. (your screenshot is the alpha.4)
Do you have the option linked [here](https://github.com/Lymphatus/caesium-image-compressor/issues/31#issuecomment-750859143) checked? (Default is unchecked)
Is your system language set to Chinese?

**Comment by absentmemory** [comment]
OH yes ,i used alpha4. I downloaded alpha5 before and forgot to create a desktop shortcut so that I thought I was using alpha5. Alpha5 is ok to compress pictures with filename in Chinese.
This option is unchecked, i never changed this option. And my system language set is Chinese.
I'm sorry to disturb you because of my negligence and thank you for your timely and patiently reply!

**Comment by Lymphatus** [comment]
Not a problem at all, you just confirmed the bug was solved with the alpha.5, so I'm happy with it.
Closing this issue.

Cheers!
