### ISSUE TITLE
Same folder as input doesn't work when it's ticked, but output folder is selected (alpha 5)

### ISSUE THREAD

**Issue by Rares95** [Lymphatus/caesium-image-compressor#67]
Getting a "No output folder selected" error window when I have ticked the "Same folder as input"

**Comment by Lymphatus** [comment]
I'm trying to reproduce this but I can't. Can you provide me a screenshot of the Output options? Also, which operating system are you in?

**Comment by Rares95** [comment]
I was on Windows 10, but I stopped using this and went back to the old version. It always works :/
