### ISSUE TITLE
Single Side Control Resize Enhancement Request/WishList

### ISSUE THREAD

**Issue by yxpoh** [Lymphatus/caesium-image-compressor#68]
The new long edge and short edge does make it really useful and convenient. 

However, I thought there might be a use case for when you want the width or height to be exactly the same throughout the whole conversion batch.

Like 1440 for the height, while the width gets dynamically adjusted to the aspect ratio accordingly or 2560 for the width while the height gets adjusted accordingly.

**Comment by Lymphatus** [comment]
The long/short edges option always dynamically adjust the width/height according to the aspect ratio. So, if you have a bunch of 1920x1080 and some 2880x1620 pictures and select "long edge -> 1080px", all the images will be resized to 1080x720.
The only downside to this is when you have two kind of images, for example 1920x1080 and 1080x1920: selecting long edge will always compress them to 1080x720 and 720x1080.

**Comment by yxpoh** [comment]
Yes, I understand that.

My use case is where I want a set of images to be converted to fit my monitor width regardless of image size.

Example a picture of 6000x4000 will go to 3440x2293, but a 4000x6000, will get 3440x 5159,.
This is to prevent the image from getting too pixelated when stretched.

**Comment by Lymphatus** [comment]
Added in [v2.6.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.6.0)
