### ISSUE TITLE
Failed when the name has “. ” and Crashed when select null folder

### ISSUE THREAD

**Issue by mumu-san** [Lymphatus/caesium-image-compressor#69]
1. <del> it seems that the operation Failed when the name has “. ”，which is the combination of dot and space. </del>
2. <del>sometimes the program crashed when use the "add folder" and cancel the window.</del>

also there is a suggestion, 
hope the program has a option to skip png files or convert png to jpg,
because png compressing is quite slow.

by the way, thanks for your great work.

**Comment by mumu-san** [comment]
I rechecked the first fail to process problem, and it seems that the resize function do not support some special character combination, which usually includes a 'space' .

**Comment by Lymphatus** [comment]
Can confirm it fails if an images has " . " in the name.
About the crash on cancel of the add folder, seems ok on OS X. Going to test on Windows too.

Which version are you using?
PNG compression (normal, not lossless) should be much faster on alpha.5 than alpha.4.

**Comment by mumu-san** [comment]
windows11 alpha.5
![snipaste_20210909_165622](https://user-images.githubusercontent.com/58110264/132655681-a9d0eadf-df08-42b0-9712-a99395f7758a.jpg)

and the crash happens when select nothing and cancel.

**Comment by mumu-san** [comment]
> 1. ~ it seems that the operation Failed when the name has “. ”，which is the combination of dot and space. ~
> 2. ~sometimes~ the program crashed when use the "add folder" and cancel the window.
> 
> also there is a suggestion,
> hope the program has a option to skip png files or convert png to jpg,
> because png compressing is quite slow.
> 
> by the way, thanks for your great work.
