### ISSUE TITLE
Hi, What`s your way to compile caesium for Windows?

### ISSUE THREAD

**Issue by napasa** [Lymphatus/caesium-image-compressor#7]
Do you compile it through MinGW Cross-Platform compile in linux for Windows?

**Comment by Lymphatus** [comment]
Yes, but the easiest way (by far) is to compile it using the Qt Creator, since it's a Q5 project. You would just have to import the Cs-133.pro file and you are good to go, provided you meet the requirements in the README.md

**Comment by napasa** [comment]
emmmm,thanks.

**Comment by napasa** [comment]
good. compile it by mingw-w64
