### ISSUE TITLE
Images with higher than 72DPI crashes Caesium (M1 Mac)

### ISSUE THREAD

**Issue by TomS-** [Lymphatus/caesium-image-compressor#73]
Version: v2.0.0-alpha.5 

Whenever I try to compress images that has a DPI greater than 72 Ceasium will crash.

**Comment by vishals9711** [comment]
![DSC_4921](https://user-images.githubusercontent.com/26935949/149291801-7b379c39-6094-49c5-a4a9-f230c4b949b6.jpg)

**Comment by Lymphatus** [comment]
Compresses fine on beta.2 on Mac OS (actually I'm working on beta.3 but should be the same). I'll try the same version on Windows too.

**Comment by Lymphatus** [comment]
I finally got a M3 macbook and tested version 2.7.1 with the given image. Everything seems alright.
