### ISSUE TITLE
Add WEBP support

### ISSUE THREAD

**Issue by Miraihi** [Lymphatus/caesium-image-compressor#75]
Hello Matteo, thanks for the awesome piece of software!
I'm not sure about the complexity of the task, but I think it'd be great if you add the support of WEBP format to Caesium. It'll remove the huge hassle of converting the images back and forth to compress them if I choose to use WEBP. Best regards, a power user of Caesium Image Compressor.

**Comment by Lymphatus** [comment]
Added in v2.0.0-beta.2
