### ISSUE TITLE
Drag & drop of directories fail

### ISSUE THREAD

**Issue by chocolatechipcats** [Lymphatus/caesium-image-compressor#79]
Caesium 2.0.0-beta.1, Windows 10 Home (x64)

Dragging and dropping a directory full of images into the Caesium window doesn't import the images. Dragging and dropping the images directly does.

Tested this with both Windows Explorer and a third-party file manager.

Small QoL thing, probably low priority. Thanks in advance.

**Comment by Lymphatus** [comment]
Added in v2.0.0-beta.2
