### ISSUE TITLE
Can caesium become a command line tool or dll for .net framework to invoke?

### ISSUE THREAD

**Issue by suyanhanx** [Lymphatus/caesium-image-compressor#8]
I want to find a library to compress images for c#. 
Your caesium seems to have a good performance. I like to use it.
But how to compile it to a library file?

**Comment by Lymphatus** [comment]
Hi,

Caesium is not meant as a library for .NET Framework in the first place.
But this tool uses [libcaesium](https://github.com/Lymphatus/libcaesium) which, unfortunately, is a C library.
Instead, if you don't mind using a command line tool, you can try [caesium-clt](https://github.com/Lymphatus/caesium-clt) which is in a pretty good state. Actually there're no binaries available for the latest version, but I'm working on it.
The fastest option - once I will make a binary release - would be to invoke caesium-clt from your application.

Let me know if you have any further question.

**Comment by suyanhanx** [comment]
Oh, thank you for your reply. I'll try to make a library from libcaesium firstly.

Waiting for your binary release.
