### ISSUE TITLE
[Discuss] Option to automatically convert to another format

### ISSUE THREAD

**Issue by wideocean** [Lymphatus/caesium-image-compressor#80]
In the stable version, when compressing PNG files, it automatically converts the image files to JPEG. Since JPEG is always smaller than PNG, I really loved that feature.
However, I'm switching to MacOS so I can only use the beta version currently. The only thing I'm missing here is the automatic conversion to JPG.

Please consider to implement the option to automatically convert to JPG when compressing e.g. PNGs.

Thanks and good work, keep it up.

**Comment by virgil-av** [comment]
Recently used  this app and this feature to convert to other format is one of core value, I wish the stable version had a  "to webp" option.  The only problem the stable version has is the lack of multithreading which makes it slow compared to the new version. 

I do understand you want the app to do one thing, which is compression, converting images is also compression,  as long as you convert other formats like PNG, TIFF, BMP to JPG or WEBP.

**Comment by robsonsobral** [comment]
Just to note that you can convert to JXL without lose the original JPG.

**Comment by TonySen1** [comment]
I really need the ability to convert formats, so I still use version 1.7.0

**Comment by JFMugen** [comment]
I think an option to convert PNG (or other supported format) to JPG or maybe WebP would be useful for someone who needs smaller file size without a specific format, it would remove the need of another tool. I think it fits to the "compression program" as well. 

You can disable Lossless option when user choose convert option as well so I don't think it is an issue?

**Comment by Lymphatus** [comment]
Thanks for the feedback everybody.
As far as I can tell, the conversion was a pretty loved feature. I get it's super convenient - like resizing is - and right now it's a bummer if you were used to the 1.7.0 and want to switch to 2.0.0+. I try to value the community feedback, especially from long-time users, a lot more than my vision, so yeah, there we go.

Right now I'm working on a couple of features for the next release, then I think I will focus on this topic. I'm not entirely sure how - I've something in mind but it's just a bunch of ideas - but at least for the formats currently supported (JPG, PNG and WebP) it should work.

A problem I can see for the future is handling less common formats (see [here](https://github.com/Lymphatus/libcaesium/issues)), but we'll see.

**Comment by MoneyAllDay** [comment]
I just wanna add up that this feature is almost a must it's because when converting/compressing to JPG with Caesium the size of the file is incredibly low with surprisingly good quality(at 80+ for me) and i don't know of any other software that keeps the quality/size ratios as good as Caesium.

Yes PNG has a transparency feature that JPG doesn't have but i think maybe a warning pointing that out is better than removing the conversion altogether.

When i needed good image quality and low file size i immediately thought of Caesium and all i had to do was 2 clicks, drag the images and click compress, it honestly doesn't get any better than that. It really was the best part of Caesium, quick and good.

**Comment by Lymphatus** [comment]
Just released [v2.3.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.3.0) with this feature.

**Comment by JFMugen** [comment]
> Just released [v2.3.0](https://github.com/Lymphatus/caesium-image-compressor/releases/tag/v2.3.0) with this feature.

Just checked few days ago to see whether there is an update about this or not, awesome ^^

**Comment by morphinestyle** [comment]
I can't found any way use this new feature...
How can i convert?

**Comment by Lymphatus** [comment]
On versions 2.3+ you can find it in the Output tab. Screenshot (macOS version, Windows is basically the same) attached.
<img width="539" alt="Screenshot 2023-02-03 alle 15 57 21" src="https://user-images.githubusercontent.com/12133996/216635402-13dc3019-fba2-4da4-96ad-53cb80abc418.png">
