### ISSUE TITLE
Possible Bug: Failure to complete on long process

### ISSUE THREAD

**Issue by Saijin-Naib** [Lymphatus/caesium-image-compressor#83]
**Describe the bug**
After a long optimization, Caesium failed to "complete" the optimization, though by all indications (CPU, RAM, Net) it is done and not working any longer.

**Software version**
The version of Caesium Image Compressor [e.g. 2.0.0-beta.1]
2.0.0-beta.2

**Operating System information**
Windows 11 21H2 22000.318

**To Reproduce**
1) Drag/drop folder
2) Optimize all in-place
3) Wait (1hr+)
4) Keep task open and computer awake over night
5) 12+hr later, job still stuck on 99%

**Expected behavior**
I expect that an optimization job will finish and show the summary UI and release locks on the files.

**Screenshots**
![image](https://user-images.githubusercontent.com/19295950/141494978-fa93b82a-a057-4514-bf6d-926c98f2a11d.png)

![image](https://user-images.githubusercontent.com/19295950/141495051-f3bc3cc8-9815-4884-b6e1-2e8346823e6a.png)

**Additional context**
Working over a mounted network drive.

**Comment by Lymphatus** [comment]
Interface seems frozen at the start of the process. Were all the images compressed, as far as could tell by looking at the files?

**Comment by Saijin-Naib** [comment]
As far as I can tell, yes.
