### ISSUE TITLE
Wrong Original size showed after compression finished.

### ISSUE THREAD

**Issue by Blackbytes-max** [Lymphatus/caesium-image-compressor#86]
**Describe the bug**
 The right original size is 3.96Gb but Wrong Original size showed in the window after comnpression finished is -34.58Mb .

**Software version**
 2.0.0-beta.2

**Operating System information**
Windows 11 21H2 22000.346

**To Reproduce**
1. Turn 'Keep folder structure' on
2. Click on 'Add folder' and select original file
3. Click on 'Compress' and wait 
4. Comnpression finished and see error

**Screenshots**
![Snipaste_2021-11-23_10-25-59](https://user-images.githubusercontent.com/52771689/142964637-2584572f-56c1-4687-bedd-6af124346876.jpg)
![Snipaste_2021-11-23_10-32-18](https://user-images.githubusercontent.com/52771689/142964699-5cb66dbd-538f-4b52-80b4-81f4d3e784f9.jpg)

**Additional context**
Original file has a directory contains 115 subfolders and the total number of original image files is 1796.

**Comment by Lymphatus** [comment]
Confirmed to be a visual bug of the final dialog (and the statusbar, if you look at it).
Thanks for reporting.
