### ISSUE TITLE
"b" used for bytes instead of "B"

### ISSUE THREAD

**Issue by vhouriet** [Lymphatus/caesium-image-compressor#87]
A lower case "b" indicates a bit whereas an upper case "B" indicate a byte (8 bits). In caesium, lower case "b" are used to say byte, which is against the convention. It looks like this is intended behaviour, but it is very misleading.

Example :
![image](https://user-images.githubusercontent.com/89147152/144031513-114632b7-1528-4134-8367-5f5f0a4090e6.png)

**Comment by Lymphatus** [comment]
You're right, thanks for pointing it out. I'll fix it in the next release.
