### ISSUE TITLE
Image conversion along with compression

### ISSUE THREAD

**Issue by cesc34** [Lymphatus/caesium-image-compressor#89]
The original Caesium allowed you to convert from PNG to JPG for some extra file size savings. Will that be an option now? Also WebP conversion would be a wonderful addition.

**Comment by Lymphatus** [comment]
This is very similar to #80, so the [answer is basically the same as there](https://github.com/Lymphatus/caesium-image-compressor/issues/80#issuecomment-951631523). 

Closing this and keeping the other up. I will think about bringing the conversion feature back.
