### ISSUE TITLE
Bug: Exif data stripped

### ISSUE THREAD

**Issue by MaurizioRicci** [Lymphatus/caesium-image-compressor#9]
If you try to compress images with replace in the same directory, then image's exif data will be stripped from photos (even if there is active the option to keep exif data)

Se provi a comprimere le foto rimpiazzando gli originali il programma rimuove i dati exif dalle foto (anche se nelle opzioni è spuntato il flag per tenere gli exif)

**Comment by starmoonxp** [comment]
save issue
