### ISSUE TITLE
Application Error (crash)

### ISSUE THREAD

**Issue by ArmynC** [Lymphatus/caesium-image-compressor#90]
**Describe the bug**
The application is crashing at launch.

**Software version**
2.0.0 - beta 2

**Operating System information**
 - OS: Windows
 - Version: 7

**Screenshots**
![Capture](https://user-images.githubusercontent.com/16375271/146587244-35ef125a-6a70-4297-9060-6d81be8c3fee.PNG)

**Comment by ArmynC** [comment]
**Update:**

### Beta v1 -

Unable to launch due to a missing function in API (_most of the required apps are installed already on this system_).
![beta1](https://user-images.githubusercontent.com/16375271/146670360-9931c2fb-5351-4a5a-8db7-83c729cbcdbb.png)

### Alpa v5 (and older?) -

Working, the caveat being that the compress session is stuck at 0%.

![alpha5](https://user-images.githubusercontent.com/16375271/146670449-8b03b1bd-cfe4-42f6-98fd-b073f6248d70.png)

**Comment by Lymphatus** [comment]
Are you on a 32bit version of Windows? Since beta I dropped the 32bit support.

**Comment by ArmynC** [comment]
Nope, x64 Windows 7 with the latest updates (inc. LTS).

**Comment by Lymphatus** [comment]
I've not tested Windows 7 myself, but should indeed work.

The alpha issue with the very long time processing a PNG is a bug of that version, not related to your startup problems. Since beta I switched to another compiler, so I think that's the issue. I'll run some more tests.

**Comment by garywill** [comment]
Same here. Crash on Windows 7 x64 2.0.0-beta3 on starting up

1.7.0 runs
