### ISSUE TITLE
The files in the translations folder are not loaded, only English (US) and Italiano are available

### ISSUE THREAD

**Issue by ZJKUSO** [Lymphatus/caesium-image-compressor#92]
The files in the translations folder are not loaded, only English (US) and Italiano are available
And two requests
1、Save resize settings automatically
2、Put the "clear" and "select all" buttons next to "add" and "remove".

**Comment by Lymphatus** [comment]
Version 2.0.0 currently has only English and Italian translations. Old translations won't work anymore.
