### ISSUE TITLE
Installation: Sudden reboot caused by Visual C++ redistributables?

### ISSUE THREAD

**Issue by chocolatechipcats** [Lymphatus/caesium-image-compressor#95]
I opened Caesium and got a notification that there was a new update. I allowed it to download and begin installation of the new version. Then my computer rebooted without warning, which is definitely undesired behaviour.

Looking into the event logs and reliability history showed that the reboot was triggered by the installer for Visual C++ redistributables. Googling this shows that it's happened in other places as well:

https://superuser.com/questions/1487595/microsoft-visual-c-2017-installer-forces-automatic-reboot
https://stackoverflow.com/questions/26047861/how-can-i-suppress-a-forced-restart-caused-by-my-bootstrapper
https://docs.microsoft.com/en-us/answers/questions/29352/when-does-visual-c-2015-2019-redistributable-lead.html
https://github.com/sqlitebrowser/sqlitebrowser/issues/1119

Hopefully this can be fixed.

**Comment by Lymphatus** [comment]
You are correct, the new version installs VC++ if not present in the system, but should definitely not reboot without a warning. I disabled the automatic update while I investigate further. Thanks for the report.

**Comment by chocolatechipcats** [comment]
The first link indicates that the /norestart flag should prevent it.

**Comment by Lymphatus** [comment]
Yes, the installer calls it with `/quiet /install /norestart`, so it's a bit strange.

**Comment by Lymphatus** [comment]
Fixed in beta.4.
