### ISSUE TITLE
Allow to order items by Size/Resolution/Saved

### ISSUE THREAD

**Issue by cacamille3** [Lymphatus/caesium-image-compressor#96]
First, thanks for the tool you provide.

**Is your feature request related to a problem? Please describe.**
No issue here

**Describe the solution you'd like**
Allow order by clicking on the column header

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Lymphatus** [comment]
Coming in beta.4 for sure.

**Comment by Lymphatus** [comment]
Fixed in beta.4.
