### ISSUE TITLE
Application crash without any error

### ISSUE THREAD

**Issue by YoshimasaNegishi** [Lymphatus/caesium-image-compressor#97]
**Describe the bug**
When click "Compress" button, the compressing window is popup.
However the progress is 0%. then, the application crash.
Zero byte temporal file is created in output folder.

**Software version**
2.0.0-beta.1
2.0.0-beta.2
2.0.0-beta.3

**Operating System information**
 - OS: Windows
 - Version: 11

**To Reproduce**
1. Click 'add'
2. Select picture(s)
2. Click 'Compress'

**Additional context**
2.0.0-alpha.4 works

**Comment by Lymphatus** [comment]
Does it happen with every set of images you try, or just a particular one? Can you try with just one single image and let me know?

**Comment by YoshimasaNegishi** [comment]
Regardless the number of images, it's same behavior.
It seems that all photos(JPEG) which were taken my NIKON D7200 have same problem.
Others, e.g. download jpeg file from website is OK.
Unfortunately, I cannot upload sample data here because the size is more than 10MB.

**Comment by YoshimasaNegishi** [comment]
![DSC_5503](https://user-images.githubusercontent.com/19618440/151655551-dde8bbb4-f281-4e69-967b-3df2a96c5594.JPG)
Found an sample file less than 10MB which crash application. please find attached one.

**Comment by Lymphatus** [comment]
The library underneath has an issue with that image on Windows only. I managed to get the error, I'll try a fix.

**Comment by Lymphatus** [comment]
Should be fixed in beta.4
