### ISSUE TITLE
add logo in uninstaller data windows

### ISSUE THREAD

**Issue by Asgatlat** [Lymphatus/caesium-image-compressor#99]
the program icon is missing in uninstaller data in windows : 

![image](https://user-images.githubusercontent.com/86599367/152150626-b24ca84d-555f-4617-82be-20512667de31.png)

you should add : 

`[WriteRegStr]` HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\caesium" "DisplayIcon" "$INSTDIR\caesium.ico"

**Comment by Asgatlat** [comment]
FYI same bug with 2.0.0 beta 3 ;)

**Comment by Lymphatus** [comment]
Fixed in beta.4.
